In [145]:
import os
import json
import pandas as pd
import networkx
import numpy as np
import obonet  # conda install -c biobuilds obonet
import datetime
from dateutil.parser import parse
import pytz

In [146]:
go_obo_file = "../data/disprot/go-basic.obo"

# Mongo collections
disprot_old_file = "../data/disprot/disprot8.entries_2023_12.json"
#disprot_new_file = "../data/disprot/disprot8.entries_2024_06_c.json"
#disprot_new_file = "../data/disprot/disprot8.entries_2024_12_c.json"  # 29 October 2024 (10:15 CET)
disprot_new_file = "../data/disprot/disprot8.entries_2025_06_c.json"  # 1 July 2025 (15:55 CEST)

region_date_threshold = parse("2023/12/31")
region_date_threshold = pytz.utc.localize(region_date_threshold)
print(region_date_threshold)

invalid_regions_file = "../data/disprot/invalid_regions_fullCAID3.tsv"  # Victoria's validation on binding
accession_whitelist_file = None #"../data/accession_filter.txt"  # Limit the reference to these accessions
accession_blacklist_file = "../data/disprot/blacklist"

# Download from SIFTS
sifts_file = "../data/sifts/uniprot_segments_observed.tsv.gz"

# Output
references_dir = "../data/output/references"
dataset_raw_file = "../data/output/dataset_raw.tsv"
dataset_ec_file = "../data/output/dataset_ec.tsv"
challenge_terms_file = "../data/output/challenge_terms.tsv"
dataset_file = "../data/output/dataset.tsv"
fasta_new_file = "../data/output/homology/disprot_new.fasta"
fasta_old_file = "../data/output/homology/disprot_old.fasta"

2023-12-31 00:00:00+00:00

In [147]:
def expand_region(df_:pd.DataFrame, start_col:str='start', end_col:str='end', res_col:str='reg_position') -> pd.DataFrame:
    df_[res_col] = list(range(int(df_[start_col]), int(df_[end_col]) + 1, 1))
    return df_

def expand_sequence(df_:pd.DataFrame, seq_column:str='sequence', res_col:str='seq_aa') -> pd.DataFrame:
    df_[res_col] = [(i+1, aa) for i, aa in enumerate(df_[seq_column])]
    return df_

## Associate DisProt annotation terms to CAID challenges

In [148]:
# IDPO terms
data_idpo = [
            ('IDPO:00076', 'disorder', 'disorder'), ('IDPO:00077', 'disorder', 'molten-globule'), ('IDPO:00078', 'disorder', 'pre-molten-globule'), 
    
            ('IDPO:00502', 'linker', 'flexible linker/spacer'),
    
            ('IDPO:00049', 'transition'), 
            ('IDPO:00050', 'transition'), ('IDPO:00051', 'transition'), ('IDPO:00052', 'transition'), ('IDPO:00053', 'transition'), ('IDPO:00060', 'transition'), ('IDPO:00055', 'transition'), 
            ('IDPO:00056', 'transition'), ('IDPO:00061', 'transition'), ('IDPO:00054', 'transition'), ('IDPO:00057', 'transition'), ('IDPO:00058', 'transition'), ('IDPO:00059', 'transition')]

# ('IDPO:00501', 'linker', 'entropic chain'),  ('IDPO:00503', 'linker', 'flexible C-terminal tail'), ('IDPO:00504', 'linker', 'flexible N-terminal tail')

# GO ancestor terms corresponding to CAID2 challenges
ancestors = {'GO:0005488': 'binding', 'GO:0003676': 'binding nucleic acid', 'GO:0005515': 'binding protein'}

In [149]:
# The OBO must have "ontology: GO" header (first line)
graph = obonet.read_obo(go_obo_file)

# Remove all edges which are not "is_a"
to_remove = []
for e in graph.edges:
    if e[2] != 'is_a':
        to_remove.append((e[0], e[1]))
for ele in to_remove:
    graph.remove_edge(*ele)
    
# Create children table
data_go = []    
for node in graph.nodes(data=True):
    challenge = ancestors.get(node[0])
    if challenge is not None:
        data_go.append([node[0], challenge])
        for children in networkx.ancestors(graph, node[0]): 
            data_go.append([children, challenge])

In [150]:
df_challenge = pd.DataFrame(data=data_idpo + data_go, columns=['term_id', 'challenge', 'term_name']).drop_duplicates()
df_challenge.to_csv(challenge_terms_file, sep="\t", index=False)
df_challenge

         term_id        challenge               term_name
0     IDPO:00076         disorder                disorder
1     IDPO:00077         disorder          molten-globule
2     IDPO:00078         disorder      pre-molten-globule
3     IDPO:00502           linker  flexible linker/spacer
4     IDPO:00049       transition                    None
...          ...              ...                     ...
3062  GO:0001664  binding protein                    None
3063  GO:0030911  binding protein                    None
3064  GO:0031698  binding protein                    None
3065  GO:0042011  binding protein                    None
3066  GO:0005151  binding protein                    None

[3067 rows x 3 columns]

## Process DisProt annotations

In [151]:
# Get DisProt annotations (mjson format)
# disprot_old = {}
# with open(disprot_old_file, "r") as f:
#     for line in f:
#         obj = json.loads(line)
#         disprot_old[obj["disprot_id"]] = obj
#
# disprot_new = {}
# with open(disprot_new_file, "r") as f:
#     for line in f:
#         obj = json.loads(line)
#         disprot_new[obj["disprot_id"]] = obj

In [152]:
# Get DisProt annotations (json format)
disprot_old = {}
with open(disprot_old_file, "r") as f:
     for obj in json.load(f):
         disprot_old[obj["disprot_id"]] = obj

# From downlaod or export from compass
disprot_new = {}
with open(disprot_new_file, "r") as f:
     for obj in json.load(f):
         disprot_new[obj["disprot_id"]] = obj
         
# From a mongoexport of the collection
# disprot_new = {}
# with open(disprot_new_file, "r") as f:
#     for line in f:
#         print(line)
#         obj = json.loads(line)
#         disprot_new[obj["disprot_id"]] = obj

# Print one region as example
# print(disprot_new[list(disprot_new.keys())[0]]['regions'][0])

In [153]:
old_sequences = set()
for k in disprot_old:
    old_sequences.add(disprot_old[k]['sequence'])

black_list_regions = set()
if invalid_regions_file is not None:
    df_ = pd.read_csv(invalid_regions_file, sep="\t")
    black_list_regions = set(df_.loc[df_['valid']!=1, "region_id"].tolist())

# Filter accession given an input list
white_list = set()
if accession_whitelist_file is not None:
    with open(accession_whitelist_file) as f:
        for line in f:
            white_list.add(line.strip())

black_list = set()
if accession_blacklist_file is not None:
    with open(accession_blacklist_file) as f:
        for line in f:
            black_list.add(line.strip())

print(len(white_list), len(black_list), len(black_list_regions))

0 13 99

In [154]:
# Get new annotations (delta = new - old)
dataset = []  # New valid annotations
for disprot_id in disprot_new:
    if disprot_id not in disprot_old:
        if "obsolete" not in disprot_new[disprot_id]:
            if disprot_new[disprot_id]['sequence'] not in old_sequences:
                if "X" not in disprot_new[disprot_id]["sequence"]:
                    if not white_list or disprot_id in white_list:
                        if not black_list or disprot_id not in black_list:
                            obj = disprot_new[disprot_id].copy()

                            regions = []
                            for region in obj["regions"]:
                                if "obsolete" not in region:
                                    if region['region_id'] not in black_list_regions:
                                        if region.get('validated') or region.get('curator_id') in ['vnugnes', 'fquaglia']:
                                            # and parse(region.get('date'))>region_date_threshold]
                                            regions.append(region)
                                        else:
                                            print("{} not-validated region".format(region['region_id']))
                                    else:
                                        print("{} invalid region (blacklisted)".format(region['region_id']))
                                else:
                                    print("{} obsolete region".format(region['region_id']))

                            if regions:
                                obj["regions"] = regions
                                dataset.append(obj)
                            else:
                                print("{} excluded, only obsolete/invalid regions".format(disprot_id))
                        else:
                            print("{} excluded, is in black list".format(disprot_id))
                    else:
                        print("{} excluded, not in white list".format(disprot_id))
                else:
                    print("{} excluded, contains X".format(disprot_id))
            else:
                print("{} excluded, old sequence".format(disprot_id))
        else:
            print("{} excluded, obsolete entry".format(disprot_id))
print(len(dataset))

DP02354 excluded, obsolete entry
DP02362r001 obsolete regions
DP02362r002 obsolete regions
DP02362r004 obsolete regions
DP02362 excluded, only obsolete/invalid regions
DP02366 excluded, obsolete entry
DP02450 excluded, only obsolete/invalid regions
DP02560 excluded, obsolete entry
DP02582 excluded, obsolete entry
DP02720 excluded, obsolete entry
DP02902 excluded, only obsolete/invalid regions
DP02906 excluded, only obsolete/invalid regions
DP02932 excluded, only obsolete/invalid regions
DP02938 excluded, only obsolete/invalid regions
DP02942 excluded, only obsolete/invalid regions
DP02952 excluded, only obsolete/invalid regions
DP02955 excluded, only obsolete/invalid regions
DP02963 excluded, only obsolete/invalid regions
DP02974 excluded, only obsolete/invalid regions
DP02997 excluded, only obsolete/invalid regions
DP02998 excluded, only obsolete/invalid regions
DP03009 excluded, only obsolete/invalid regions
DP03036 excluded, only obsolete/invalid regions
DP03051 excluded, contains X
DP03077 excluded, only obsolete/invalid regions
DP03084 excluded, only obsolete/invalid regions
DP03086 excluded, obsolete entry
DP03089 excluded, obsolete entry
DP03097 excluded, only obsolete/invalid regions
DP03103 excluded, only obsolete/invalid regions
DP03117 excluded, obsolete entry
DP03128 excluded, only obsolete/invalid regions
DP03146 excluded, only obsolete/invalid regions
DP03165 excluded, only obsolete/invalid regions
DP03183 excluded, obsolete entry
DP03188 excluded, only obsolete/invalid regions
DP03194 excluded, obsolete entry
DP03208 excluded, only obsolete/invalid regions
DP03244 excluded, only obsolete/invalid regions
DP03247 excluded, only obsolete/invalid regions
DP03252 excluded, only obsolete/invalid regions
DP03321 excluded, obsolete entry
DP03370 excluded, only obsolete/invalid regions
DP03371 excluded, only obsolete/invalid regions
DP03375 excluded, only obsolete/invalid regions
DP03384 excluded, only obsolete/invalid regions
DP03443 excluded, only obsolete/invalid regions
DP03462 excluded, only obsolete/invalid regions
DP03463 excluded, only obsolete/invalid regions
DP03468 excluded, only obsolete/invalid regions
DP03474 excluded, only obsolete/invalid regions
DP03478 excluded, only obsolete/invalid regions
DP03484 excluded, only obsolete/invalid regions
DP03491 excluded, only obsolete/invalid regions
DP03493 excluded, only obsolete/invalid regions
DP03602 excluded, only obsolete/invalid regions
DP03603 excluded, only obsolete/invalid regions
DP03640 excluded, obsolete entry
DP03658 excluded, obsolete entry
DP03668 excluded, only obsolete/invalid regions
DP03673 excluded, obsolete entry
DP03678 excluded, obsolete entry
DP03679 excluded, obsolete entry
DP03696 excluded, obsolete entry
DP03720 excluded, obsolete entry
DP03736 excluded, obsolete entry
DP03745r003 obsolete regions
DP03747r001 not-validated region
DP03747r002 not-validated region
DP03747r003 not-validated region
DP03747r004 not-validated region
DP03747r005 not-validated region
DP03747r006 not-validated region
DP03747 excluded, only obsolete/invalid regions
DP03750r001 not-validated region
DP03750 excluded, only obsolete/invalid regions
DP03752r001 not-validated region
DP03752 excluded, only obsolete/invalid regions
DP03753r001 not-validated region
DP03753 excluded, only obsolete/invalid regions
DP03754 excluded, only obsolete/invalid regions
DP03757 excluded, obsolete entry
DP03758r008 invalid region (blacklisted)
DP03758r009 invalid region (blacklisted)
DP03758r010 invalid region (blacklisted)
DP03762 excluded, obsolete entry
DP03763 excluded, obsolete entry
DP03785 excluded, obsolete entry
DP03796 excluded, obsolete entry
DP03806r003 invalid region (blacklisted)
DP03806r004 invalid region (blacklisted)
DP03808 excluded, obsolete entry
DP03818r008 obsolete regions
DP03818r012 not-validated region
DP03819r002 obsolete regions
DP03826r004 obsolete regions
DP03826r005 obsolete regions
DP03826r006 obsolete regions
DP03858 excluded, obsolete entry
DP03883 excluded, obsolete entry
DP03888r002 obsolete regions
DP03888r003 obsolete regions
DP03898r003 obsolete regions
DP03914r002 invalid region (blacklisted)
DP03915r002 obsolete regions
DP03932 excluded, obsolete entry
DP03936 excluded, obsolete entry
DP03940r001 obsolete regions
DP03974r003 obsolete regions
DP03980r005 invalid region (blacklisted)
DP03981 excluded, obsolete entry
DP03982r003 invalid region (blacklisted)
DP03982r004 invalid region (blacklisted)
DP03983 excluded, only obsolete/invalid regions
DP03986 excluded, obsolete entry
DP03987 excluded, only obsolete/invalid regions
DP03988r005 invalid region (blacklisted)
DP03988r006 invalid region (blacklisted)
DP03990r004 invalid region (blacklisted)
DP04001 excluded, obsolete entry
DP04004r001 obsolete regions
DP04004r002 obsolete regions
DP04004r003 obsolete regions
DP04004r004 obsolete regions
DP04004r005 obsolete regions
DP04004 excluded, only obsolete/invalid regions
DP04009r002 obsolete regions
DP04009r004 obsolete regions
DP04010r002 obsolete regions
DP04010r003 obsolete regions
DP04011r002 obsolete regions
DP04011r004 obsolete regions
DP04012r002 obsolete regions
DP04012r004 obsolete regions
DP04013r003 obsolete regions
DP04013r004 obsolete regions
DP04013 excluded, only obsolete/invalid regions
DP04014r004 invalid region (blacklisted)
DP04014r005 invalid region (blacklisted)
DP04014r006 invalid region (blacklisted)
DP04015r001 obsolete regions
DP04015r004 obsolete regions
DP04016r004 obsolete regions
DP04017r002 obsolete regions
DP04017r008 invalid region (blacklisted)
DP04017r009 obsolete regions
DP04020r002 obsolete regions
DP04020r003 invalid region (blacklisted)
DP04020r004 invalid region (blacklisted)
DP04020r005 invalid region (blacklisted)
DP04020r008 invalid region (blacklisted)
DP04020r009 invalid region (blacklisted)
DP04020r010 invalid region (blacklisted)
DP04020r011 invalid region (blacklisted)
DP04021 excluded, obsolete entry
DP04025 excluded, only obsolete/invalid regions
DP04029r001 obsolete regions
DP04029r002 obsolete regions
DP04029r003 obsolete regions
DP04031 excluded, obsolete entry
DP04033r005 invalid region (blacklisted)
DP04034 excluded, obsolete entry
DP04035r002 obsolete regions
DP04036r004 obsolete regions
DP04042r002 obsolete regions
DP04043 excluded, obsolete entry
DP04047r001 obsolete regions
DP04047 excluded, only obsolete/invalid regions
DP04053 excluded, obsolete entry
DP04073 excluded, old sequence
DP04085r001 obsolete regions
DP04085 excluded, only obsolete/invalid regions
DP04091r002 obsolete regions
DP04097r002 obsolete regions
DP04099r001 obsolete regions
DP04099 excluded, only obsolete/invalid regions
DP04106 excluded, obsolete entry
DP04132r004 obsolete regions
DP04136 excluded, only obsolete/invalid regions
DP04141r002 invalid region (blacklisted)
DP04141r009 invalid region (blacklisted)
DP04141r012 invalid region (blacklisted)
DP04141r015 obsolete regions
DP04142r006 invalid region (blacklisted)
DP04142r007 invalid region (blacklisted)
DP04143 excluded, only obsolete/invalid regions
DP04144r007 obsolete regions
DP04144r008 obsolete regions
DP04144r009 invalid region (blacklisted)
DP04145r005 invalid region (blacklisted)
DP04145r009 obsolete regions
DP04145r010 obsolete regions
DP04146 excluded, only obsolete/invalid regions
DP04147r001 not-validated region
DP04147 excluded, only obsolete/invalid regions
DP04150 excluded, obsolete entry
DP04161r005 obsolete regions
DP04161r013 invalid region (blacklisted)
DP04161r014 invalid region (blacklisted)
DP04161r020 invalid region (blacklisted)
DP04161r021 invalid region (blacklisted)
DP04162r001 not-validated region
DP04162 excluded, only obsolete/invalid regions
DP04167r004 invalid region (blacklisted)
DP04167r006 invalid region (blacklisted)
DP04167r008 invalid region (blacklisted)
DP04167r010 invalid region (blacklisted)
DP04167r011 invalid region (blacklisted)
DP04168 excluded, only obsolete/invalid regions
DP04172r003 invalid region (blacklisted)
DP04177r004 invalid region (blacklisted)
DP04177r005 invalid region (blacklisted)
DP04181 excluded, obsolete entry
DP04186r002 obsolete regions
DP04190r004 obsolete regions
DP04190r010 invalid region (blacklisted)
DP04190r011 invalid region (blacklisted)
DP04190r012 invalid region (blacklisted)
DP04193r002 obsolete regions
DP04193r003 obsolete regions
DP04194 excluded, obsolete entry
DP04195r002 obsolete regions
DP04199r003 invalid region (blacklisted)
DP04199r004 invalid region (blacklisted)
DP04199r005 invalid region (blacklisted)
DP04199r006 invalid region (blacklisted)
DP04199r009 invalid region (blacklisted)
DP04200r003 invalid region (blacklisted)
DP04204 excluded, only obsolete/invalid regions
DP04205 excluded, only obsolete/invalid regions
DP04206 excluded, obsolete entry
DP04207 excluded, only obsolete/invalid regions
DP04208r002 obsolete regions
DP04208r003 obsolete regions
DP04208r005 obsolete regions
DP04209 excluded, obsolete entry
DP04210r001 obsolete regions
DP04211r003 obsolete regions
DP04211r006 invalid region (blacklisted)
DP04212r001 obsolete regions
DP04212r002 obsolete regions
DP04212r003 obsolete regions
DP04212r004 obsolete regions
DP04212r005 obsolete regions
DP04212r006 obsolete regions
DP04212 excluded, only obsolete/invalid regions
DP04213 excluded, only obsolete/invalid regions
DP04218r002 obsolete regions
DP04218r003 invalid region (blacklisted)
DP04218r007 invalid region (blacklisted)
DP04218r008 invalid region (blacklisted)
DP04218r009 invalid region (blacklisted)
DP04219r001 obsolete regions
DP04222 excluded, obsolete entry
DP04223 excluded, obsolete entry
DP04224 excluded, only obsolete/invalid regions
DP04235r005 invalid region (blacklisted)
DP04235r006 invalid region (blacklisted)
DP04238 excluded, only obsolete/invalid regions
DP04241r002 invalid region (blacklisted)
DP04243r005 invalid region (blacklisted)
DP04243r006 invalid region (blacklisted)
DP04243r007 invalid region (blacklisted)
DP04243r008 invalid region (blacklisted)
DP04243r009 invalid region (blacklisted)
DP04244r004 invalid region (blacklisted)
DP04244r005 invalid region (blacklisted)
DP04244r011 obsolete regions
DP04244r012 obsolete regions
DP04245r001 obsolete regions
DP04245 excluded, only obsolete/invalid regions
DP04246r002 obsolete regions
DP04246r003 obsolete regions
DP04250r003 obsolete regions
DP04254 excluded, only obsolete/invalid regions
DP04255r003 invalid region (blacklisted)
DP04260r001 obsolete regions
DP04260r002 obsolete regions
DP04260r003 obsolete regions
DP04264r005 invalid region (blacklisted)
DP04264r006 invalid region (blacklisted)
DP04264r009 invalid region (blacklisted)
DP04264r010 invalid region (blacklisted)
DP04264r013 invalid region (blacklisted)
DP04264r014 invalid region (blacklisted)
DP04265 excluded, obsolete entry
DP04266r001 obsolete regions
DP04266 excluded, only obsolete/invalid regions
DP04269 excluded, only obsolete/invalid regions
DP04272r001 not-validated region
DP04272r002 not-validated region
DP04272r003 not-validated region
DP04272 excluded, only obsolete/invalid regions
DP04280r006 invalid region (blacklisted)
DP04280r007 invalid region (blacklisted)
DP04282r001 obsolete regions
DP04282 excluded, only obsolete/invalid regions
DP04283r002 not-validated region
DP04287r003 not-validated region
DP04287r004 not-validated region
DP04289r001 obsolete regions
DP04289r002 obsolete regions
DP04289r003 obsolete regions
DP04289r004 obsolete regions
DP04289r005 obsolete regions
DP04289r006 obsolete regions
DP04289 excluded, only obsolete/invalid regions
DP04290r002 obsolete regions
DP04291 excluded, obsolete entry
DP04292 excluded, only obsolete/invalid regions
DP04293 excluded, obsolete entry
DP04298r010 invalid region (blacklisted)
DP04298r011 invalid region (blacklisted)
DP04298r017 obsolete regions
DP04302r001 not-validated region
DP04303r001 not-validated region
DP04303 excluded, only obsolete/invalid regions
DP04304r001 not-validated region
DP04304r002 not-validated region
DP04304r003 not-validated region
DP04304r004 not-validated region
DP04305r001 not-validated region
DP04305r002 not-validated region
DP04305r003 not-validated region
DP04305r004 not-validated region
DP04305r005 not-validated region
DP04305 excluded, only obsolete/invalid regions
DP04307r001 not-validated region
DP04307r002 not-validated region
DP04307r003 not-validated region
DP04307 excluded, only obsolete/invalid regions
DP04308r001 not-validated region
DP04308r011 invalid region (blacklisted)
DP04309r001 obsolete regions
DP04309r002 obsolete regions
DP04310r001 not-validated region
DP04310 excluded, only obsolete/invalid regions
DP04311r001 not-validated region
DP04311r002 not-validated region
DP04311 excluded, only obsolete/invalid regions
DP04312r001 not-validated region
DP04312 excluded, only obsolete/invalid regions
DP04313r001 not-validated region
DP04313 excluded, only obsolete/invalid regions
DP04314r001 not-validated region
DP04314r002 not-validated region
DP04314r003 not-validated region
DP04314r004 not-validated region
DP04314r005 not-validated region
DP04314 excluded, only obsolete/invalid regions
DP04315r001 not-validated region
DP04315 excluded, only obsolete/invalid regions
DP04316r001 not-validated region
DP04316 excluded, only obsolete/invalid regions
DP04317r001 not-validated region
DP04317r002 not-validated region
DP04317 excluded, only obsolete/invalid regions
DP04318r001 not-validated region
DP04318 excluded, only obsolete/invalid regions
DP04319r001 not-validated region
DP04319 excluded, only obsolete/invalid regions
DP04320r001 not-validated region
DP04320 excluded, only obsolete/invalid regions
DP04321 excluded, obsolete entry
DP04322 excluded, only obsolete/invalid regions
DP04323 excluded, obsolete entry
DP04326 excluded, is in black list
DP04327r001 not-validated region
DP04327r002 not-validated region
DP04327r003 not-validated region
DP04327r004 not-validated region
DP04327r005 not-validated region
DP04327r006 not-validated region
DP04327r007 not-validated region
DP04327r008 not-validated region
DP04327r009 not-validated region
DP04327r010 not-validated region
DP04327r011 not-validated region
DP04327r012 not-validated region
DP04327 excluded, only obsolete/invalid regions
DP04328r001 not-validated region
DP04328r002 not-validated region
DP04328r003 not-validated region
DP04328r004 not-validated region
DP04328r005 obsolete regions
DP04329r001 obsolete regions
DP04329r002 obsolete regions
DP04329r003 obsolete regions
DP04329 excluded, only obsolete/invalid regions
DP04330r001 not-validated region
DP04330r002 obsolete regions
DP04330r003 obsolete regions
DP04330r004 obsolete regions
DP04330r005 obsolete regions
DP04330r006 obsolete regions
DP04330r007 obsolete regions
DP04330 excluded, only obsolete/invalid regions
DP04331 excluded, obsolete entry
DP04332r001 not-validated region
DP04332r002 not-validated region
DP04332r003 not-validated region
DP04332r004 not-validated region
DP04332r005 not-validated region
DP04332r006 not-validated region
DP04332r007 not-validated region
DP04332r008 not-validated region
DP04332r009 not-validated region
DP04332r010 not-validated region
DP04332r011 not-validated region
DP04332 excluded, only obsolete/invalid regions
DP04333 excluded, obsolete entry
DP04334r001 not-validated region
DP04334 excluded, only obsolete/invalid regions
DP04335 excluded, obsolete entry
DP04336r001 not-validated region
DP04336 excluded, only obsolete/invalid regions
DP04337r001 obsolete regions
DP04337r004 invalid region (blacklisted)
DP04337r008 obsolete regions
DP04338 excluded, only obsolete/invalid regions
DP04339r001 not-validated region
DP04339r002 not-validated region
DP04339r003 not-validated region
DP04339r004 not-validated region
DP04339r005 not-validated region
DP04339r006 not-validated region
DP04339r007 not-validated region
DP04339 excluded, only obsolete/invalid regions
DP04342r001 not-validated region
DP04342r002 not-validated region
DP04342r003 not-validated region
DP04342 excluded, only obsolete/invalid regions
DP04343r003 invalid region (blacklisted)
DP04345 excluded, obsolete entry
DP04346 excluded, only obsolete/invalid regions
DP04347r001 not-validated region
DP04347r002 not-validated region
DP04347r003 not-validated region
DP04347r004 not-validated region
DP04347r005 not-validated region
DP04347r006 not-validated region
DP04347r007 not-validated region
DP04347r008 not-validated region
DP04347r009 not-validated region
DP04347r010 not-validated region
DP04348r001 obsolete regions
DP04349r001 obsolete regions
DP04349r002 obsolete regions
DP04350r001 obsolete regions
DP04350r002 obsolete regions
DP04350r003 obsolete regions
DP04350r004 obsolete regions
DP04350r005 obsolete regions
DP04350r006 obsolete regions
DP04350r007 obsolete regions
DP04350r008 obsolete regions
DP04350r009 obsolete regions
DP04350r010 obsolete regions
DP04350r011 obsolete regions
DP04350r012 obsolete regions
DP04350 excluded, only obsolete/invalid regions
DP04351 excluded, only obsolete/invalid regions
DP04353r001 not-validated region
DP04353 excluded, only obsolete/invalid regions
DP04354r001 not-validated region
DP04354 excluded, only obsolete/invalid regions
DP04355r001 not-validated region
DP04355 excluded, only obsolete/invalid regions
DP04356r001 not-validated region
DP04356 excluded, only obsolete/invalid regions
DP04357r001 not-validated region
DP04357 excluded, only obsolete/invalid regions
DP04358r001 not-validated region
DP04358r002 not-validated region
DP04358r003 not-validated region
DP04358r004 not-validated region
DP04358r005 not-validated region
DP04358r006 not-validated region
DP04358r007 not-validated region
DP04358 excluded, only obsolete/invalid regions
DP04359r001 not-validated region
DP04359r002 not-validated region
DP04359 excluded, only obsolete/invalid regions
DP04360r001 not-validated region
DP04360r002 not-validated region
DP04360r003 not-validated region
DP04360 excluded, only obsolete/invalid regions
DP04361r001 not-validated region
DP04361r002 not-validated region
DP04361 excluded, only obsolete/invalid regions
DP04362r001 not-validated region
DP04362r002 not-validated region
DP04362r003 not-validated region
DP04362 excluded, only obsolete/invalid regions
DP04363r001 not-validated region
DP04363r002 not-validated region
DP04363 excluded, only obsolete/invalid regions
DP04364r001 not-validated region
DP04364r002 not-validated region
DP04364 excluded, only obsolete/invalid regions
DP04365 excluded, obsolete entry
DP04366r001 not-validated region
DP04366r002 not-validated region
DP04366 excluded, only obsolete/invalid regions
DP04367 excluded, obsolete entry
DP04369r003 obsolete regions
DP04370r002 obsolete regions
DP04374r001 not-validated region
DP04374 excluded, only obsolete/invalid regions
DP04376r004 obsolete regions
DP04378r003 obsolete regions
DP04379r003 obsolete regions
DP04382r001 not-validated region
DP04382r002 not-validated region
DP04382r003 not-validated region
DP04382r004 not-validated region
DP04382r005 not-validated region
DP04382r006 not-validated region
DP04382r007 not-validated region
DP04382 excluded, only obsolete/invalid regions
DP04386r002 obsolete regions
DP04387r003 obsolete regions
DP04388r004 invalid region (blacklisted)
DP04388r005 invalid region (blacklisted)
DP04388r008 invalid region (blacklisted)
DP04388r009 invalid region (blacklisted)
DP04388r010 obsolete regions
DP04389 excluded, obsolete entry
DP04390r001 obsolete regions
DP04390r002 obsolete regions
DP04391r003 obsolete regions
DP04391r006 obsolete regions
DP04391r008 obsolete regions
DP04394r002 obsolete regions
DP04395r003 obsolete regions
DP04398r001 obsolete regions
DP04398r002 obsolete regions
DP04399r002 obsolete regions
DP04400 excluded, obsolete entry
DP04401r007 invalid region (blacklisted)
DP04401r008 invalid region (blacklisted)
DP04401r009 invalid region (blacklisted)
DP04401r013 invalid region (blacklisted)
DP04401r015 invalid region (blacklisted)
DP04401r018 invalid region (blacklisted)
DP04402 excluded, only obsolete/invalid regions

In [155]:
# Write fasta for homology calculation
with open(fasta_new_file, "w") as fout:
    for obj in dataset:
        fout.write(">{}|{}\n{}\n".format(obj['disprot_id'], obj['acc'], obj['sequence']))

with open(fasta_old_file, "w") as fout:
    for disprot_id, obj in disprot_old.items():
        if "obsolete" not in obj:
            fout.write(">{}|{}\n{}\n".format(obj['disprot_id'], obj['acc'], obj['sequence']))

In [156]:
# Convert json to dataframe
entry_columns = ['disprot_id', 'acc', 'ncbi_taxon_id', 'organism', 'sequence']
df = pd.json_normalize(data=dataset, record_path=['regions'], meta=entry_columns, meta_prefix='', record_prefix='')
df = pd.merge(left=df, right=df_challenge, how="inner", on="term_id")
df.to_csv(dataset_raw_file, sep="\t", index=False)
df.columns

Index(['term_namespace', 'ec_ontology', 'end', 'region_id', 'start', 'term_id',
       'unpublished', 'statement', 'curator_id', 'released', 'ec_name',
       'term_ontology', 'curator_name', 'reference_id', 'version',
       'reference_html', 'date', 'reference_source', 'ec_id', 'cross_refs',
       'term_name_x', 'curator_orcid', 'ec_go', 'disprot_namespace',
       'validated.curator_name', 'validated.curator_id', 'validated.timestamp',
       'term_comment', 'term_def', 'term_is_obsolete', 'term_not_annotate',
       'construct_alterations', 'sample', 'sequence_construct',
       'interaction_partner', 'conditions', 'states_connection',
       'annotation_extensions', 'validated._id.$oid', '_id.$oid', 'disprot_id',
       'acc', 'ncbi_taxon_id', 'organism', 'sequence', 'challenge',
       'term_name_y'],
      dtype='object')

In [157]:
region_columns = ["start", "end", "term_id", "ec_id", "challenge"]
df = df.loc[:, entry_columns + region_columns]
df

,disprot_id,acc,ncbi_taxon_id,organism,sequence,start,end,term_id,ec_id,challenge
0,DP02732,Q8IWJ2,9606,Homo sapiens,MEDLVQDGVASPATPGTGKSKLETLPKEDLIKFAKKQMMLIQKAKS...,1547,1569,IDPO:00076,ECO:0006220,disorder
1,DP03745,Q8VHC3,10090,Mus musculus,MSILLSPPSLLLLLAALVAPATSTTNYRPDWNRLRGLARGRVETCG...,25,34,IDPO:00076,ECO:0001238,disorder
2,DP03745,Q8VHC3,10090,Mus musculus,MSILLSPPSLLLLLAALVAPATSTTNYRPDWNRLRGLARGRVETCG...,121,145,IDPO:00076,ECO:0001238,disorder
3,DP03748,P75862,83333,Escherichia coli (strain K12),MRIKPDDNWRWYYDEEHDRMMLDLANGMLFRSRFARKMLTPDAFSP...,169,180,IDPO:00076,ECO:0006220,disorder
4,DP03749,Q92871,9606,Homo sapiens,MAVTAQAARRKERVLCLFDVDGTLTPARQKIDPEVAAFLQKLRSRV...,1,11,IDPO:00076,ECO:0006220,disorder
...,...,...,...,...,...,...,...,...,...,...
916,DP04308,P43586,559292,Saccharomyces cerevisiae (strain ATCC 204508 /...,MAPKKPSKRQNLRREVAPEVFQDSQARNQLANVPHLTEKSAQRKPS...,1,204,GO:0033592,ECO:0001254,binding
917,DP04328,P32833,559292,Saccharomyces cerevisiae (strain ATCC 204508 /...,MLNGEDFVEHNDILSSPAKSRNVTPKRVDPHGERQLRRIHSSKKNL...,176,200,GO:0003682,ECO:0005640,binding
918,DP04401,A0AAI8ESY0,190486,Xanthomonas axonopodis pv. citri (strain 306),MKLFNRYRVALLSALPLALCALSAAAQVVQEYEYAPDRIYQVRTGL...,154,255,IDPO:00053,ECO:0006165,transition
919,DP04401,A0AAI8ESY0,190486,Xanthomonas axonopodis pv. citri (strain 306),MKLFNRYRVALLSALPLALCALSAAAQVVQEYEYAPDRIYQVRTGL...,154,255,IDPO:00053,ECO:0001249,transition
920,DP04401,A0AAI8ESY0,190486,Xanthomonas axonopodis pv. citri (strain 306),MKLFNRYRVALLSALPLALCALSAAAQVVQEYEYAPDRIYQVRTGL...,154,255,IDPO:00053,ECO:0006301,transition

In [158]:
# Get dataset sequences (1 residue per row)
df_sequence = df.apply(expand_sequence, axis=1).copy(deep=True).drop(columns=["ncbi_taxon_id", "organism", "start", "end", "sequence", "term_id", "ec_id", 'challenge'])
df_sequence = df_sequence.explode("seq_aa")
df_sequence[['pos', 'aa']] = pd.DataFrame(df_sequence['seq_aa'].tolist(), index=df_sequence.index)
df_sequence = df_sequence.drop(columns='seq_aa').drop_duplicates()
df_sequence

    disprot_id     acc  pos aa
0      DP02732  Q8IWJ2    1  M
0      DP02732  Q8IWJ2    2  E
0      DP02732  Q8IWJ2    3  D
0      DP02732  Q8IWJ2    4  L
0      DP02732  Q8IWJ2    5  V
..         ...     ...  ... ..
597    DP04416  O53692   93  T
597    DP04416  O53692   94  Y
597    DP04416  O53692   95  T
597    DP04416  O53692   96  G
597    DP04416  O53692   97  F

[165256 rows x 4 columns]

## Map PDB observed positions using SIFTS

In [159]:
df_sifts = pd.read_csv(sifts_file, sep="\t", header=1)
# Filter for dataset entries
df_sifts = df_sifts.loc[df_sifts['SP_PRIMARY'].isin(df_sequence['acc'])]
# Explode observed regions 
df_sifts = df_sifts.apply(expand_region, start_col="SP_BEG", end_col="SP_END", axis=1)
df_sifts = df_sifts.explode("reg_position")
df_sifts = df_sifts.loc[:, ['SP_PRIMARY', 'reg_position']].drop_duplicates().reset_index(drop=True).rename(columns={"SP_PRIMARY": "acc"})
df_sifts

/tmp/ipykernel_11651/2595968912.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sifts = pd.read_csv(sifts_file, sep="\t", header=1)

          acc reg_position
0      P0A8P8            3
1      P0A8P8            4
2      P0A8P8            5
3      P0A8P8            6
4      P0A8P8            7
...       ...          ...
74538  O60016          462
74539  Q13546          177
74540  Q13546          178
74541  Q13546          179
74542  Q13546          180

[74543 rows x 2 columns]

In [160]:
df_sequence = pd.merge(df_sequence, df_sifts, left_on=["acc", "pos"], right_on=["acc", "reg_position"], how="left")
df_sequence.rename(columns={"reg_position": "pdb"}, inplace=True)
df_sequence.loc[df_sequence['pdb'].notnull(), 'pdb'] = 1.0
df_sequence.loc[df_sequence['pdb'].notnull()]

       disprot_id     acc   pos aa  pdb
1569      DP02732  Q8IWJ2  1570  K  1.0
1570      DP02732  Q8IWJ2  1571  S  1.0
1571      DP02732  Q8IWJ2  1572  A  1.0
1572      DP02732  Q8IWJ2  1573  D  1.0
1573      DP02732  Q8IWJ2  1574  H  1.0
...           ...     ...   ... ..  ...
165251    DP04416  O53692    93  T  1.0
165252    DP04416  O53692    94  Y  1.0
165253    DP04416  O53692    95  T  1.0
165254    DP04416  O53692    96  G  1.0
165255    DP04416  O53692    97  F  1.0

[74543 rows x 5 columns]

## Define regions

Transform the per-protein dataframe into a per-residue dataframe

In [161]:
df_regions = df.apply(expand_region, axis=1).loc[:, ["disprot_id", "reg_position", "ec_id", "challenge"]].copy(deep=True)
# df_regions = pd.merge(left=df_regions, right=df_challenge, how="inner", left_on="term_id", right_on="term_id").drop(columns=["term_id"])
df_regions

,disprot_id,reg_position,ec_id,challenge
0,DP02732,"[1547, 1548, 1549, 1550, 1551, 1552, 1553, 155...",ECO:0006220,disorder
1,DP03745,"[25, 26, 27, 28, 29, 30, 31, 32, 33, 34]",ECO:0001238,disorder
2,DP03745,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...",ECO:0001238,disorder
3,DP03748,"[169, 170, 171, 172, 173, 174, 175, 176, 177, ...",ECO:0006220,disorder
4,DP03749,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]",ECO:0006220,disorder
...,...,...,...,...
916,DP04308,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",ECO:0001254,binding
917,DP04328,"[176, 177, 178, 179, 180, 181, 182, 183, 184, ...",ECO:0005640,binding
918,DP04401,"[154, 155, 156, 157, 158, 159, 160, 161, 162, ...",ECO:0006165,transition
919,DP04401,"[154, 155, 156, 157, 158, 159, 160, 161, 162, ...",ECO:0001249,transition
920,DP04401,"[154, 155, 156, 157, 158, 159, 160, 161, 162, ...",ECO:0006301,transition

In [162]:
# ECO:0006220, X-ray crystallography-based structural model with missing residue coordinates used in manual assertion  
df_ = df_regions.loc[(df_regions['challenge'] == 'disorder') & (df_regions['ec_id'] != 'ECO:0006220')]
df_.loc[:, 'challenge'] = 'disorder_nox'
df_regions = pd.concat([df_regions, df_])
df_regions

,disprot_id,reg_position,ec_id,challenge
0,DP02732,"[1547, 1548, 1549, 1550, 1551, 1552, 1553, 155...",ECO:0006220,disorder
1,DP03745,"[25, 26, 27, 28, 29, 30, 31, 32, 33, 34]",ECO:0001238,disorder
2,DP03745,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...",ECO:0001238,disorder
3,DP03748,"[169, 170, 171, 172, 173, 174, 175, 176, 177, ...",ECO:0006220,disorder
4,DP03749,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]",ECO:0006220,disorder
...,...,...,...,...
850,DP04154,"[156, 157, 158, 159, 160, 161, 162, 163, 164, ...",ECO:0007689,disorder_nox
893,DP04271,"[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 3...",ECO:0006230,disorder_nox
894,DP04401,"[154, 155, 156, 157, 158, 159, 160, 161, 162, ...",ECO:0006165,disorder_nox
895,DP04401,"[154, 155, 156, 157, 158, 159, 160, 161, 162, ...",ECO:0001249,disorder_nox
896,DP04401,"[154, 155, 156, 157, 158, 159, 160, 161, 162, ...",ECO:0006301,disorder_nox

In [163]:
df_regions_all = df_regions.drop(columns=['ec_id']).explode("reg_position").drop_duplicates()
df_regions_all['has_region'] = 1
df_regions_all

    disprot_id reg_position     challenge  has_region
0      DP02732         1547      disorder           1
0      DP02732         1548      disorder           1
0      DP02732         1549      disorder           1
0      DP02732         1550      disorder           1
0      DP02732         1551      disorder           1
..         ...          ...           ...         ...
893    DP04271          205  disorder_nox           1
893    DP04271          206  disorder_nox           1
893    DP04271          207  disorder_nox           1
893    DP04271          208  disorder_nox           1
893    DP04271          209  disorder_nox           1

[67947 rows x 4 columns]

In [164]:
# Create the pivot table. Transpose challenge values into columns 
df_regions_all = pd.pivot_table(
    df_regions_all,
    columns="challenge",
    index=['disprot_id', 'reg_position'],
    values='has_region')
df_regions_all = df_regions_all.reset_index()
df_regions_all

challenge,disprot_id,reg_position,binding,binding nucleic acid,binding protein,disorder,disorder_nox,linker,transition
0,DP02732,1547,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,DP02732,1548,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,DP02732,1549,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,DP02732,1550,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,DP02732,1551,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
31439,DP04416,93,NaN,NaN,NaN,1.0,1.0,NaN,NaN
31440,DP04416,94,NaN,NaN,NaN,1.0,1.0,NaN,NaN
31441,DP04416,95,NaN,NaN,NaN,1.0,1.0,NaN,NaN
31442,DP04416,96,NaN,NaN,NaN,1.0,1.0,NaN,NaN
31443,DP04416,97,NaN,NaN,NaN,1.0,1.0,NaN,NaN

In [165]:
# Add sequence positions not mapping to any DisProt region
df_regions_all = pd.merge(left=df_regions_all, right=df_sequence, how="right", left_on=["disprot_id", "reg_position"], right_on=["disprot_id", "pos"])
df_regions_all.drop(columns="reg_position", inplace=True)
df_regions_all

,disprot_id,binding,binding nucleic acid,binding protein,disorder,disorder_nox,linker,transition,acc,pos,aa,pdb
0,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,1,M,NaN
1,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,2,E,NaN
2,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,3,D,NaN
3,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,4,L,NaN
4,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,5,V,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
165251,DP04416,NaN,NaN,NaN,1.0,1.0,NaN,NaN,O53692,93,T,1.0
165252,DP04416,NaN,NaN,NaN,1.0,1.0,NaN,NaN,O53692,94,Y,1.0
165253,DP04416,NaN,NaN,NaN,1.0,1.0,NaN,NaN,O53692,95,T,1.0
165254,DP04416,NaN,NaN,NaN,1.0,1.0,NaN,NaN,O53692,96,G,1.0
165255,DP04416,NaN,NaN,NaN,1.0,1.0,NaN,NaN,O53692,97,F,1.0

## Write files

Challenge definitions

- The first list are the columns to be considered as positive (any)
- The second list (mask) are the columns to be considered as negative (any)
- If the second list is not provided all non-positives are considered negatives
- In case of conflicts, the positives always overwrite the negatives
- If mask is provided proteins without at least one residue that could be masked (even when overwritten by a positive) are excluded (e.g. only proteins with PDB observed residues are considered)

In [166]:
# Reorder the columns
head_cols = ['disprot_id', 'acc', 'pos', 'aa']
disprot_cols = list(df_challenge['challenge'].unique())
other_cols = sorted(list((set(df_regions_all.columns.tolist()) - set(head_cols)) - set(disprot_cols)))
cols = head_cols + disprot_cols + other_cols
df_regions_all = df_regions_all[cols]
df_regions_all

,disprot_id,acc,pos,aa,disorder,linker,transition,binding nucleic acid,binding,binding protein,disorder_nox,pdb
0,DP02732,Q8IWJ2,1,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DP02732,Q8IWJ2,2,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DP02732,Q8IWJ2,3,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DP02732,Q8IWJ2,4,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DP02732,Q8IWJ2,5,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
165251,DP04416,O53692,93,T,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0
165252,DP04416,O53692,94,Y,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0
165253,DP04416,O53692,95,T,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0
165254,DP04416,O53692,96,G,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0
165255,DP04416,O53692,97,F,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0

In [167]:
# Write the dataframe
df_regions_all.to_csv(dataset_file, sep="\t", index=False)

### Write references (Fasta format)

* The next element overwrites the previous in the "class" list
* The "fill" field is used to fill unassigned positions
* Only proteins with at least a "1" are written to file

In [168]:
challenges = {'linker': {'class': [('linker', '1')], 'fill': '0'}, 
              'linker_disorder': {'class': [('disorder', '0'), ('linker', '1')], 'fill': '-'},
              'disorder': {'class': [('disorder', '1')], 'fill': '0'}, 
              'disorder_nox': {'class': [('disorder_nox', '1')], 'fill': '0'}, 
              'disorder_pdb': {'class': [('pdb', '0'), ('disorder', '1')], 'fill': '-'},
              'disorder_pdb_fill': {'class': [('pdb', '0'), ('disorder', '1')], 'fill': '1'},
              'binding': {'class': [('binding', '1')], 'fill': '0'},
              'binding_nucleic_acid': {'class': [('binding nucleic acid', '1')], 'fill': '0'},
              'binding_disorder': {'class': [('disorder', '0'), ('binding', '1')], 'fill': '-'},
             }

for file_name, challenge in challenges.items():
    with open("{}/{}.fasta".format(references_dir, file_name), "w") as fout:
        for disprot_id, df_g in df_regions_all.groupby('disprot_id'):
            df_g['output'] = np.nan
            # Assign class
            for column, value in challenge['class']:
                df_g.loc[df_g[column].notnull(), 'output'] = value
            # Fill
            if df_g['output'].notnull().any() and challenge.get('fill'):
                df_g.loc[df_g['output'].isnull(), 'output'] = challenge['fill'] 
            # Write proteins with at least one positive assignment
            if (df_g['output'] == '1').any():
                fout.write(">{}\n{}\n{}\n".format(disprot_id, "".join(df_g['aa']), "".join(df_g['output'])))

```
# New proteins (data)
grep ">" disorder_pdb.fasta | sed 's/>//' > ~/tmp1

# Old proteins (data_caid3_b)
grep ">" disorder_pdb.fasta | sed 's/>//' > ~/tmp2

# Get new sequences
comm -32 tmp1 tmp2 > disprot_2025_06_new.txt

# Extract fasta of the new sequences
awk 'BEGIN{while((getline<"Projects/caid2-reference/data/output/homology/disprot_new.fasta")>0){if (substr($1,1,1)==">") acc=substr($1,2,7); else diz[acc]=$1}}{if ($1 in diz) printf ">%s\n%s\n",$1,diz[$1]}' disprot_2025_06_new.txt > disprot_2025_06_new.fasta
```