In [27]:
import os
import pandas as pd
import numpy as np
import requests

In [28]:
dataset_file = "../data/output/dataset.tsv"
prediction_dir = "../data/predictions"
predictions_references_file = "../data/predictor_class.csv"

assessment_disorder_file = "../data/assessment_results/disorder.analysis.all.dataset.f1s.metrics.csv"
assessment_binding_file = "../data/assessment_results/binding.analysis.all.dataset.f1s.metrics.csv"

# Output
dataset_merge_file = "../data/output/dataset_merge.tsv"

In [29]:
# It assumes one method participate in only one challenge
df_challenge = pd.read_csv(predictions_references_file, sep=",")
df_challenge
# df_challenge[df_challenge['Method'] == 'ENSHROUD-all']

                  group          predictor  disorder  binding
0               ESpritz          ESpritz-D      True    False
1               ESpritz          ESpritz-X      True    False
2               ESpritz          ESpritz-N      True    False
3                  RONN               RONN      True    False
4                  CLIP               CLIP     False     True
..                  ...                ...       ...      ...
97   AlphaFold-disorder      AlphaFold-rsa      True    False
98   AlphaFold-disorder  AlphaFold-binding     False     True
99       SPOT-Disorder2     SPOT-Disorder2      True    False
100          ESMDisPred       ESMDisPred-2      True    False
101          ESMDisPred    ESMDisPred-2PDB      True    False

[102 rows x 4 columns]

In [30]:
df_1 = pd.read_csv(assessment_disorder_file, index_col=0).reset_index().rename(columns={'index': 'method'})[['method', 'thr']]
df_1['challenge'] = 'disorder'

df_2 = pd.read_csv(assessment_binding_file, index_col=0).reset_index().rename(columns={'index': 'method'})[['method', 'thr']]
df_2['challenge'] = 'binding'

df_ = pd.concat([df_1, df_2])

df_thresholds = df_.loc[df_['method'].isin(df_challenge[df_challenge['disorder'] == 1]['predictor']) & (df_['challenge'] == 'disorder')]
df_thresholds = pd.concat([df_thresholds, df_.loc[df_['method'].isin(df_challenge[df_challenge['binding'] == 1]['predictor']) & (df_['challenge'] == 'binding')]])
df_thresholds['thr'].astype('float32')
df_thresholds

                 method    thr challenge
0             ESpritz-D  0.338  disorder
1             ESpritz-X  0.110  disorder
2             ESpritz-N  0.433  disorder
3                  RONN  0.560  disorder
5        DISOPRED3-diso  0.430  disorder
..                  ...    ...       ...
84  DeepDRPBind-protein  0.020   binding
85      DeepDRPBind-DNA  0.507   binding
86      DeepDRPBind-RNA  0.012   binding
94               LIPNet  0.447   binding
98    AlphaFold-binding  0.669   binding

[102 rows x 3 columns]

In [31]:
df_list = []
for pred_file in os.listdir(prediction_dir):
    pred_name = pred_file[:-5]  
    if pred_name in df_thresholds['method'].values:
        # print(pred_name)
        data = []
        with open("{}/{}".format(prediction_dir, pred_file)) as f:
            for line in f:
                if line[0] == ">":
                    disprot_id = line[1:].strip()
                else:
                    data.append([pred_name, disprot_id] + line[:-1].split("\t"))

        if len(data[0]) == 6:
            df_ = pd.DataFrame(data, columns=['method', 'disprot_id', 'pos', 'aa', 'score', 'class'])
        else:
            df_ = pd.DataFrame(data, columns=['method', 'disprot_id', 'pos', 'aa', 'score'])
            df_['class'] = np.nan

        if (df_['class'] == "").any():
            print("Empty class, filling with nan", pred_name)
            df_.loc[df_['class'] == "", 'class'] = np.nan
        df_['class'] = df_['class'].astype('float32')

        if (df_['score'] == "").any():
            print("Empty score, filling with nan", pred_name)
            df_.loc[df_['score'] == "", 'score'] = np.nan
        df_['score'] = df_['score'].astype('float32')

        df_.loc[df_['score'] >= df_thresholds.loc[df_thresholds['method'] == pred_name, 'thr'].iloc[0], 'class'] = 1

        if 'AlphaFold' in pred_name:
            df_['class'] = df_['score']

        df_.drop(columns=['aa', 'score'], inplace=True)
        df_list.append(df_)
    else:
        print("missing method threshold", pred_name)

df_pred = pd.concat(df_list)    
df_pred

Empty class, filling with nan IPA-All-bind
Empty score, filling with nan NeProc-binding
Empty class, filling with nan OPAL
Empty class, filling with nan IPA-AF2-Linker
Empty class, filling with nan AlphaFold-rsa
Empty class, filling with nan DisEMBL-disHL
Empty class, filling with nan DisEMBL-dis465
Empty class, filling with nan RONN
Empty class, filling with nan AlphaFold-binding
Empty class, filling with nan IPA-Nucleotide-bind
Empty class, filling with nan AIUPred-2-binding
Empty score, filling with nan flDPnn3b
Empty class, filling with nan AIUPred-2-disorder
Empty class, filling with nan AlphaFold-pLDDT
Empty class, filling with nan rawMSA
Empty class, filling with nan MoRFchibi
Empty class, filling with nan DisoMine
Empty score, filling with nan FoldUnfold
Empty class, filling with nan IPA-Protein-bind
Empty score, filling with nan NeProc-disorder
Empty class, filling with nan IPA-AF2-Protein-bind

               method disprot_id pos  class
0          IDP-Fusion    DP02732   1    1.0
1          IDP-Fusion    DP02732   2    1.0
2          IDP-Fusion    DP02732   3    1.0
3          IDP-Fusion    DP02732   4    1.0
4          IDP-Fusion    DP02732   5    1.0
...               ...        ...  ..    ...
95423  Metapredict-v3    DP04186  76    0.0
95424  Metapredict-v3    DP04186  77    0.0
95425  Metapredict-v3    DP04186  78    0.0
95426  Metapredict-v3    DP04186  79    0.0
95427  Metapredict-v3    DP04186  80    0.0

[9574794 rows x 4 columns]

In [32]:
df_pred['pos'] = df_pred['pos'].astype(int)
df_pred = pd.merge(df_pred, df_challenge, left_on=['method'], right_on=['predictor'], how='left').drop(columns='predictor')
df_pred

                 method disprot_id  pos  class        group  disorder  binding
0            IDP-Fusion    DP02732    1    1.0   IDP-Fusion      True    False
1            IDP-Fusion    DP02732    2    1.0   IDP-Fusion      True    False
2            IDP-Fusion    DP02732    3    1.0   IDP-Fusion      True    False
3            IDP-Fusion    DP02732    4    1.0   IDP-Fusion      True    False
4            IDP-Fusion    DP02732    5    1.0   IDP-Fusion      True    False
...                 ...        ...  ...    ...          ...       ...      ...
9574789  Metapredict-v3    DP04186   76    0.0  Metapredict      True    False
9574790  Metapredict-v3    DP04186   77    0.0  Metapredict      True    False
9574791  Metapredict-v3    DP04186   78    0.0  Metapredict      True    False
9574792  Metapredict-v3    DP04186   79    0.0  Metapredict      True    False
9574793  Metapredict-v3    DP04186   80    0.0  Metapredict      True    False

[9574794 rows x 7 columns]

In [33]:
df_pred_binding = pd.pivot_table(df_pred.loc[df_pred['binding'] == 1], index=['disprot_id', 'pos'], columns=['method'], values=['class'])
df_pred_disorder = pd.pivot_table(df_pred.loc[df_pred['disorder'] == 1], index=['disprot_id', 'pos'], columns=['method'], values=['class'])

In [34]:
df_pred_binding.columns = df_pred_binding.columns.set_levels(['binding'], level=0)
df_pred_disorder.columns = df_pred_disorder.columns.set_levels(['disorder'], level=0)
df_pred = pd.merge(df_pred_disorder, df_pred_binding, on=['disprot_id', 'pos'])
df_pred

               disorder                                             \
method          AIUPred AIUPred-2-disorder APOD AUCpred-no-profile
disprot_id pos
DP02732    1        1.0                1.0  1.0                1.0
           2        1.0                1.0  1.0                1.0
           3        1.0                1.0  1.0                1.0
           4        1.0                1.0  1.0                1.0
           5        1.0                1.0  1.0                1.0
...                 ...                ...  ...                ...
DP04186    76       0.0                NaN  1.0                0.0
           77       0.0                NaN  1.0                0.0
           78       1.0                NaN  1.0                0.0
           79       1.0                NaN  1.0                0.0
           80       1.0                NaN  1.0                1.0

                                                                          \
method         AUCpred-profile AlphaFold-pLDDT AlphaFold-rsa DARUMA-beta
disprot_id pos
DP02732    1               1.0           0.621         0.860         1.0
           2               1.0           0.676         0.865         1.0
           3               1.0           0.653         0.868         1.0
           4               1.0           0.665         0.869         1.0
           5               1.0           0.658         0.875         1.0
...                        ...             ...           ...         ...
DP04186    76              0.0           0.215         0.505         0.0
           77              0.0           0.173         0.501         0.0
           78              0.0           0.134         0.477         0.0
           79              0.0           0.121         0.489         0.0
           80              1.0           0.153         0.469         0.0

                                          ...         binding                \
method         DISOPRED3-diso DeepIDP-2L  ... MoRFchibi-light MoRFchibi-web
disprot_id pos                            ...
DP02732    1              1.0        1.0  ...             1.0           1.0
           2              1.0        1.0  ...             1.0           1.0
           3              1.0        1.0  ...             1.0           1.0
           4              1.0        1.0  ...             1.0           1.0
           5              1.0        1.0  ...             0.0           1.0
...                       ...        ...  ...             ...           ...
DP04186    76             0.0        0.0  ...             1.0           1.0
           77             0.0        0.0  ...             1.0           1.0
           78             0.0        0.0  ...             1.0           1.0
           79             0.0        0.0  ...             1.0           1.0
           80             0.0        0.0  ...             1.0           1.0

                                                                        \
method         NeProc-binding OPAL ProBiPred-nucleic ProBiPred-protein
disprot_id pos
DP02732    1              1.0  1.0               0.0               1.0
           2              1.0  1.0               0.0               1.0
           3              1.0  1.0               0.0               1.0
           4              1.0  1.0               0.0               1.0
           5              1.0  1.0               0.0               1.0
...                       ...  ...               ...               ...
DP04186    76             0.0  1.0               0.0               1.0
           77             0.0  1.0               0.0               1.0
           78             0.0  1.0               0.0               1.0
           79             0.0  1.0               0.0               1.0
           80             0.0  1.0               0.0               1.0

                                                                \
method         bindEmbed21IDR-idrGeneral bindEmbed21IDR-idrNuc
disprot_id pos
DP02732    1                         1.0                   1.0
           2                         1.0                   1.0
           3                         1.0                   1.0
           4                         1.0                   1.0
           5                         1.0                   1.0
...                                  ...                   ...
DP04186    76                        1.0                   1.0
           77                        1.0                   1.0
           78                        1.0                   1.0
           79                        1.0                   1.0
           80                        1.0                   1.0


method         bindEmbed21IDR-rawGeneral bindEmbed21IDR-rawNuc
disprot_id pos
DP02732    1                         1.0                   1.0
           2                         1.0                   1.0
           3                         1.0                   1.0
           4                         1.0                   1.0
           5                         1.0                   1.0
...                                  ...                   ...
DP04186    76                        1.0                   1.0
           77                        1.0                   1.0
           78                        1.0                   1.0
           79                        1.0                   1.0
           80                        1.0                   1.0

[95428 rows x 102 columns]

In [35]:
df_dataset = pd.read_csv(dataset_file, sep="\t", index_col=False)
df_dataset

,disprot_id,acc,pos,aa,disorder,linker,transition,binding nucleic acid,binding,binding protein,disorder_nox,pdb
0,DP02732,Q8IWJ2,1,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DP02732,Q8IWJ2,2,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DP02732,Q8IWJ2,3,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DP02732,Q8IWJ2,4,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DP02732,Q8IWJ2,5,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
95449,DP04186,C7G3K3,76,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
95450,DP04186,C7G3K3,77,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
95451,DP04186,C7G3K3,78,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
95452,DP04186,C7G3K3,79,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
95453,DP04186,C7G3K3,80,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [36]:
df_dataset.columns = pd.MultiIndex.from_product([['reference'], df_dataset.columns])
df_dataset

       reference                                            \
      disprot_id     acc pos aa disorder linker transition
0        DP02732  Q8IWJ2   1  M      NaN    NaN        NaN
1        DP02732  Q8IWJ2   2  E      NaN    NaN        NaN
2        DP02732  Q8IWJ2   3  D      NaN    NaN        NaN
3        DP02732  Q8IWJ2   4  L      NaN    NaN        NaN
4        DP02732  Q8IWJ2   5  V      NaN    NaN        NaN
...          ...     ...  .. ..      ...    ...        ...
95449    DP04186  C7G3K3  76  D      NaN    NaN        NaN
95450    DP04186  C7G3K3  77  C      NaN    NaN        NaN
95451    DP04186  C7G3K3  78  V      NaN    NaN        NaN
95452    DP04186  C7G3K3  79  C      NaN    NaN        NaN
95453    DP04186  C7G3K3  80  S      NaN    NaN        NaN


      binding nucleic acid binding binding protein disorder_nox  pdb
0                      NaN     NaN             NaN          NaN  NaN
1                      NaN     NaN             NaN          NaN  NaN
2                      NaN     NaN             NaN          NaN  NaN
3                      NaN     NaN             NaN          NaN  NaN
4                      NaN     NaN             NaN          NaN  NaN
...                    ...     ...             ...          ...  ...
95449                  NaN     NaN             NaN          NaN  1.0
95450                  NaN     NaN             NaN          NaN  1.0
95451                  NaN     NaN             NaN          NaN  1.0
95452                  NaN     NaN             NaN          NaN  1.0
95453                  NaN     NaN             NaN          NaN  1.0

[95454 rows x 12 columns]

In [37]:
df_dataset = pd.merge(df_dataset, df_pred, left_on=[('reference', 'disprot_id'), ('reference', 'pos')], right_on=['disprot_id', 'pos'], how='left')
df_dataset

       reference                                            \
      disprot_id     acc pos aa disorder linker transition
0        DP02732  Q8IWJ2   1  M      NaN    NaN        NaN
1        DP02732  Q8IWJ2   2  E      NaN    NaN        NaN
2        DP02732  Q8IWJ2   3  D      NaN    NaN        NaN
3        DP02732  Q8IWJ2   4  L      NaN    NaN        NaN
4        DP02732  Q8IWJ2   5  V      NaN    NaN        NaN
...          ...     ...  .. ..      ...    ...        ...
95449    DP04186  C7G3K3  76  D      NaN    NaN        NaN
95450    DP04186  C7G3K3  77  C      NaN    NaN        NaN
95451    DP04186  C7G3K3  78  V      NaN    NaN        NaN
95452    DP04186  C7G3K3  79  C      NaN    NaN        NaN
95453    DP04186  C7G3K3  80  S      NaN    NaN        NaN

                                                    ...         binding  \
      binding nucleic acid binding binding protein  ... MoRFchibi-light
0                      NaN     NaN             NaN  ...             1.0
1                      NaN     NaN             NaN  ...             1.0
2                      NaN     NaN             NaN  ...             1.0
3                      NaN     NaN             NaN  ...             1.0
4                      NaN     NaN             NaN  ...             0.0
...                    ...     ...             ...  ...             ...
95449                  NaN     NaN             NaN  ...             1.0
95450                  NaN     NaN             NaN  ...             1.0
95451                  NaN     NaN             NaN  ...             1.0
95452                  NaN     NaN             NaN  ...             1.0
95453                  NaN     NaN             NaN  ...             1.0

                                                                             \
      MoRFchibi-web NeProc-binding OPAL ProBiPred-nucleic ProBiPred-protein
0               1.0            1.0  1.0               0.0               1.0
1               1.0            1.0  1.0               0.0               1.0
2               1.0            1.0  1.0               0.0               1.0
3               1.0            1.0  1.0               0.0               1.0
4               1.0            1.0  1.0               0.0               1.0
...             ...            ...  ...               ...               ...
95449           1.0            0.0  1.0               0.0               1.0
95450           1.0            0.0  1.0               0.0               1.0
95451           1.0            0.0  1.0               0.0               1.0
95452           1.0            0.0  1.0               0.0               1.0
95453           1.0            0.0  1.0               0.0               1.0

                                                       \
      bindEmbed21IDR-idrGeneral bindEmbed21IDR-idrNuc
0                           1.0                   1.0
1                           1.0                   1.0
2                           1.0                   1.0
3                           1.0                   1.0
4                           1.0                   1.0
...                         ...                   ...
95449                       1.0                   1.0
95450                       1.0                   1.0
95451                       1.0                   1.0
95452                       1.0                   1.0
95453                       1.0                   1.0


      bindEmbed21IDR-rawGeneral bindEmbed21IDR-rawNuc
0                           1.0                   1.0
1                           1.0                   1.0
2                           1.0                   1.0
3                           1.0                   1.0
4                           1.0                   1.0
...                         ...                   ...
95449                       1.0                   1.0
95450                       1.0                   1.0
95451                       1.0                   1.0
95452                       1.0                   1.0
95453                       1.0                   1.0

[95454 rows x 114 columns]

In [38]:
df_dataset.set_index([('reference', 'disprot_id'), ('reference', 'acc'), ('reference', 'pos'), ('reference', 'aa')], append=True, inplace=True)
df_dataset.index.names = [None, 'disprot_id', 'acc', 'pos', 'aa']
df_dataset

                               reference                    \
                                disorder linker transition
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M        NaN    NaN        NaN
1     DP02732    Q8IWJ2 2   E        NaN    NaN        NaN
2     DP02732    Q8IWJ2 3   D        NaN    NaN        NaN
3     DP02732    Q8IWJ2 4   L        NaN    NaN        NaN
4     DP02732    Q8IWJ2 5   V        NaN    NaN        NaN
...                                  ...    ...        ...
95449 DP04186    C7G3K3 76  D        NaN    NaN        NaN
95450 DP04186    C7G3K3 77  C        NaN    NaN        NaN
95451 DP04186    C7G3K3 78  V        NaN    NaN        NaN
95452 DP04186    C7G3K3 79  C        NaN    NaN        NaN
95453 DP04186    C7G3K3 80  S        NaN    NaN        NaN

                                                                             \
                               binding nucleic acid binding binding protein
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                   NaN     NaN             NaN
1     DP02732    Q8IWJ2 2   E                   NaN     NaN             NaN
2     DP02732    Q8IWJ2 3   D                   NaN     NaN             NaN
3     DP02732    Q8IWJ2 4   L                   NaN     NaN             NaN
4     DP02732    Q8IWJ2 5   V                   NaN     NaN             NaN
...                                             ...     ...             ...
95449 DP04186    C7G3K3 76  D                   NaN     NaN             NaN
95450 DP04186    C7G3K3 77  C                   NaN     NaN             NaN
95451 DP04186    C7G3K3 78  V                   NaN     NaN             NaN
95452 DP04186    C7G3K3 79  C                   NaN     NaN             NaN
95453 DP04186    C7G3K3 80  S                   NaN     NaN             NaN

                                                 disorder                     \
                               disorder_nox  pdb  AIUPred AIUPred-2-disorder
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M           NaN  NaN      1.0                1.0
1     DP02732    Q8IWJ2 2   E           NaN  NaN      1.0                1.0
2     DP02732    Q8IWJ2 3   D           NaN  NaN      1.0                1.0
3     DP02732    Q8IWJ2 4   L           NaN  NaN      1.0                1.0
4     DP02732    Q8IWJ2 5   V           NaN  NaN      1.0                1.0
...                                     ...  ...      ...                ...
95449 DP04186    C7G3K3 76  D           NaN  1.0      0.0                NaN
95450 DP04186    C7G3K3 77  C           NaN  1.0      0.0                NaN
95451 DP04186    C7G3K3 78  V           NaN  1.0      1.0                NaN
95452 DP04186    C7G3K3 79  C           NaN  1.0      1.0                NaN
95453 DP04186    C7G3K3 80  S           NaN  1.0      1.0                NaN

                                ...         binding                \
                                ... MoRFchibi-light MoRFchibi-web
      disprot_id acc    pos aa  ...
0     DP02732    Q8IWJ2 1   M   ...             1.0           1.0
1     DP02732    Q8IWJ2 2   E   ...             1.0           1.0
2     DP02732    Q8IWJ2 3   D   ...             1.0           1.0
3     DP02732    Q8IWJ2 4   L   ...             1.0           1.0
4     DP02732    Q8IWJ2 5   V   ...             0.0           1.0
...                             ...             ...           ...
95449 DP04186    C7G3K3 76  D   ...             1.0           1.0
95450 DP04186    C7G3K3 77  C   ...             1.0           1.0
95451 DP04186    C7G3K3 78  V   ...             1.0           1.0
95452 DP04186    C7G3K3 79  C   ...             1.0           1.0
95453 DP04186    C7G3K3 80  S   ...             1.0           1.0

                                                                      \
                               NeProc-binding OPAL ProBiPred-nucleic
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M             1.0  1.0               0.0
1     DP02732    Q8IWJ2 2   E             1.0  1.0               0.0
2     DP02732    Q8IWJ2 3   D             1.0  1.0               0.0
3     DP02732    Q8IWJ2 4   L             1.0  1.0               0.0
4     DP02732    Q8IWJ2 5   V             1.0  1.0               0.0
...                                       ...  ...               ...
95449 DP04186    C7G3K3 76  D             0.0  1.0               0.0
95450 DP04186    C7G3K3 77  C             0.0  1.0               0.0
95451 DP04186    C7G3K3 78  V             0.0  1.0               0.0
95452 DP04186    C7G3K3 79  C             0.0  1.0               0.0
95453 DP04186    C7G3K3 80  S             0.0  1.0               0.0

                                                                            \
                               ProBiPred-protein bindEmbed21IDR-idrGeneral
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                1.0                       1.0
1     DP02732    Q8IWJ2 2   E                1.0                       1.0
2     DP02732    Q8IWJ2 3   D                1.0                       1.0
3     DP02732    Q8IWJ2 4   L                1.0                       1.0
4     DP02732    Q8IWJ2 5   V                1.0                       1.0
...                                          ...                       ...
95449 DP04186    C7G3K3 76  D                1.0                       1.0
95450 DP04186    C7G3K3 77  C                1.0                       1.0
95451 DP04186    C7G3K3 78  V                1.0                       1.0
95452 DP04186    C7G3K3 79  C                1.0                       1.0
95453 DP04186    C7G3K3 80  S                1.0                       1.0

                                                      \
                               bindEmbed21IDR-idrNuc
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                    1.0
1     DP02732    Q8IWJ2 2   E                    1.0
2     DP02732    Q8IWJ2 3   D                    1.0
3     DP02732    Q8IWJ2 4   L                    1.0
4     DP02732    Q8IWJ2 5   V                    1.0
...                                              ...
95449 DP04186    C7G3K3 76  D                    1.0
95450 DP04186    C7G3K3 77  C                    1.0
95451 DP04186    C7G3K3 78  V                    1.0
95452 DP04186    C7G3K3 79  C                    1.0
95453 DP04186    C7G3K3 80  S                    1.0


                               bindEmbed21IDR-rawGeneral bindEmbed21IDR-rawNuc
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                        1.0                   1.0
1     DP02732    Q8IWJ2 2   E                        1.0                   1.0
2     DP02732    Q8IWJ2 3   D                        1.0                   1.0
3     DP02732    Q8IWJ2 4   L                        1.0                   1.0
4     DP02732    Q8IWJ2 5   V                        1.0                   1.0
...                                                  ...                   ...
95449 DP04186    C7G3K3 76  D                        1.0                   1.0
95450 DP04186    C7G3K3 77  C                        1.0                   1.0
95451 DP04186    C7G3K3 78  V                        1.0                   1.0
95452 DP04186    C7G3K3 79  C                        1.0                   1.0
95453 DP04186    C7G3K3 80  S                        1.0                   1.0

[95454 rows x 110 columns]

In [39]:
df_dataset.to_csv(dataset_merge_file, sep="\t")