In [3]:
import os
import json
import pandas as pd
import networkx
import numpy as np
import obonet  # conda install -c biobuilds obonet

In [4]:
go_obo_file = "../data/disprot/go-basic.obo"

# Mongo collections
disprot_old_file = "../data/disprot/disprot8.entries_2023_12.json"
#disprot_new_file = "../data/disprot/disprot8.entries_2024_06_c.json"
disprot_new_file = "../data/disprot/disprot8.entries_2024_12_c.json"  # 29 October 2024 (10:15 CET)

# Download from SIFTS
sifts_file = "../data/sifts/uniprot_segments_observed.tsv.gz"
accession_filter_file = None #"../data/accession_filter.txt"  # Limit the reference to these accessions

# Output
references_dir = "../data/output/references"
dataset_raw_file = "../data/output/dataset_raw.tsv"
dataset_ec_file = "../data/output/dataset_ec.tsv"
challenge_terms_file = "../data/output/challenge_terms.tsv"
dataset_file = "../data/output/dataset.tsv"
fasta_new_file = "../data/output/homology/disprot_new.fasta"
fasta_old_file = "../data/output/homology/disprot_old.fasta"

In [5]:
def expand_region(df_:pd.DataFrame, start_col:str='start', end_col:str='end', res_col:str='reg_position') -> pd.DataFrame:
    df_[res_col] = list(range(int(df_[start_col]), int(df_[end_col]) + 1, 1))
    return df_

def expand_sequence(df_:pd.DataFrame, seq_column:str='sequence', res_col:str='seq_aa') -> pd.DataFrame:
    df_[res_col] = [(i+1, aa) for i, aa in enumerate(df_[seq_column])]
    return df_

## Associate DisProt annotation terms to CAID challenges

In [6]:
# IDPO terms
data_idpo = [
            ('IDPO:00076', 'disorder', 'disorder'), ('IDPO:00077', 'disorder', 'molten-globule'), ('IDPO:00078', 'disorder', 'pre-molten-globule'), 
    
            ('IDPO:00502', 'linker', 'flexible linker/spacer'),
    
            ('IDPO:00049', 'transition'), 
            ('IDPO:00050', 'transition'), ('IDPO:00051', 'transition'), ('IDPO:00052', 'transition'), ('IDPO:00053', 'transition'), ('IDPO:00060', 'transition'), ('IDPO:00055', 'transition'), 
            ('IDPO:00056', 'transition'), ('IDPO:00061', 'transition'), ('IDPO:00054', 'transition'), ('IDPO:00057', 'transition'), ('IDPO:00058', 'transition'), ('IDPO:00059', 'transition')]

# ('IDPO:00501', 'linker', 'entropic chain'),  ('IDPO:00503', 'linker', 'flexible C-terminal tail'), ('IDPO:00504', 'linker', 'flexible N-terminal tail')

# GO ancestor terms corresponding to CAID2 challenges
ancestors = {'GO:0005488': 'binding', 'GO:0003676': 'binding nucleic acid', 'GO:0005515': 'binding protein'}

In [7]:
# The OBO must have "ontology: GO" header (first line)
graph = obonet.read_obo(go_obo_file)

# Remove all edges which are not "is_a"
to_remove = []
for e in graph.edges:
    if e[2] != 'is_a':
        to_remove.append((e[0], e[1]))
for ele in to_remove:
    graph.remove_edge(*ele)
    
# Create children table
data_go = []    
for node in graph.nodes(data=True):
    challenge = ancestors.get(node[0])
    if challenge is not None:
        data_go.append([node[0], challenge])
        for children in networkx.ancestors(graph, node[0]): 
            data_go.append([children, challenge])

In [8]:
df_challenge = pd.DataFrame(data=data_idpo + data_go, columns=['term_id', 'challenge', 'term_name']).drop_duplicates()
df_challenge.to_csv(challenge_terms_file, sep="\t", index=False)
df_challenge

         term_id        challenge               term_name
0     IDPO:00076         disorder                disorder
1     IDPO:00077         disorder          molten-globule
2     IDPO:00078         disorder      pre-molten-globule
3     IDPO:00502           linker  flexible linker/spacer
4     IDPO:00049       transition                    None
...          ...              ...                     ...
3062  GO:0017147  binding protein                    None
3063  GO:0045514  binding protein                    None
3064  GO:0031369  binding protein                    None
3065  GO:0070513  binding protein                    None
3066  GO:0000149  binding protein                    None

[3067 rows x 3 columns]

## Process DisProt annotations

In [7]:
# Get DisProt annotations (mjson format)
# disprot_old = {}
# with open(disprot_old_file, "r") as f:
#     for line in f:
#         obj = json.loads(line)
#         disprot_old[obj["disprot_id"]] = obj
#         
# disprot_new = {}
# with open(disprot_new_file, "r") as f:
#     for line in f:
#         obj = json.loads(line)
#         disprot_new[obj["disprot_id"]] = obj

In [10]:
# Get DisProt annotations (json format)
disprot_old = {}
with open(disprot_old_file, "r") as f:
     for obj in json.load(f):
         disprot_old[obj["disprot_id"]] = obj
         
# disprot_new = {}
# with open(disprot_new_file, "r") as f:
#      for obj in json.load(f):
#          disprot_new[obj["disprot_id"]] = obj
         
# From a mongoexport of the collection
disprot_new = {}
with open(disprot_new_file, "r") as f:
    for line in f:
        obj = json.loads(line)
        disprot_new[obj["disprot_id"]] = obj

In [11]:
# Get new annotations (delta = new - old)
dataset = []  # New valid annotations
for disprot_id in disprot_new:
    if disprot_id not in disprot_old and "obsolete" not in disprot_new[disprot_id]:
        if "X" not in disprot_new[disprot_id]["sequence"]:
            # Filter out obsolete regions
            disprot_new[disprot_id]["regions"] = [region for region in disprot_new[disprot_id]["regions"] if "obsolete" not in region]
            if disprot_new[disprot_id]["regions"]:
                dataset.append(disprot_new[disprot_id])
            else:
                print("{} excluded, only obsolete regions".format(disprot_id))
        else:
            print("{} excluded, contains X".format(disprot_id))

DP02362 excluded, only obsolete regions
DP02450 excluded, only obsolete regions
DP02902 excluded, only obsolete regions
DP02906 excluded, only obsolete regions
DP02932 excluded, only obsolete regions
DP02938 excluded, only obsolete regions
DP02942 excluded, only obsolete regions
DP02952 excluded, only obsolete regions
DP02955 excluded, only obsolete regions
DP02963 excluded, only obsolete regions
DP02974 excluded, only obsolete regions
DP02997 excluded, only obsolete regions
DP02998 excluded, only obsolete regions
DP03009 excluded, only obsolete regions
DP03036 excluded, only obsolete regions
DP03051 excluded, contain X
DP03077 excluded, only obsolete regions
DP03084 excluded, only obsolete regions
DP03097 excluded, only obsolete regions
DP03103 excluded, only obsolete regions
DP03128 excluded, only obsolete regions
DP03146 excluded, only obsolete regions
DP03165 excluded, only obsolete regions
DP03188 excluded, only obsolete regions
DP03208 excluded, only obsolete regions
DP03244 excluded, only obsolete regions
DP03247 excluded, only obsolete regions
DP03252 excluded, only obsolete regions
DP03370 excluded, only obsolete regions
DP03371 excluded, only obsolete regions
DP03375 excluded, only obsolete regions
DP03384 excluded, only obsolete regions
DP03443 excluded, only obsolete regions
DP03462 excluded, only obsolete regions
DP03463 excluded, only obsolete regions
DP03468 excluded, only obsolete regions
DP03474 excluded, only obsolete regions
DP03478 excluded, only obsolete regions
DP03484 excluded, only obsolete regions
DP03491 excluded, only obsolete regions
DP03493 excluded, only obsolete regions
DP03602 excluded, only obsolete regions
DP03603 excluded, only obsolete regions
DP03668 excluded, only obsolete regions
DP03747 excluded, only obsolete regions
DP03750 excluded, only obsolete regions
DP03752 excluded, only obsolete regions
DP03753 excluded, only obsolete regions
DP03754 excluded, only obsolete regions
DP03983 excluded, only obsolete regions
DP03987 excluded, only obsolete regions
DP04004 excluded, only obsolete regions
DP04013 excluded, only obsolete regions
DP04025 excluded, only obsolete regions
DP04047 excluded, only obsolete regions
DP04085 excluded, only obsolete regions
DP04099 excluded, only obsolete regions
DP04136 excluded, only obsolete regions
DP04143 excluded, only obsolete regions
DP04146 excluded, only obsolete regions
DP04168 excluded, only obsolete regions
DP04204 excluded, only obsolete regions
DP04205 excluded, only obsolete regions
DP04207 excluded, only obsolete regions
DP04213 excluded, only obsolete regions
DP04224 excluded, only obsolete regions
DP04238 excluded, only obsolete regions
DP04245 excluded, only obsolete regions

In [12]:
# WARNING
# Filter accession given an input list
if accession_filter_file is not None:
    filter_list = set()
    with open(accession_filter_file) as f:
        for line in f:
            filter_list.add(line.strip())
    dataset = list(filter(lambda x: x['disprot_id'] in filter_list, dataset))
    print(len(dataset))

In [13]:
# Write fasta for homology calculation
with open(fasta_new_file, "w") as fout:
    for obj in dataset:
        fout.write(">{}|{}\n{}\n".format(obj['disprot_id'], obj['acc'], obj['sequence']))

with open(fasta_old_file, "w") as fout:
    for disprot_id, obj in disprot_old.items():
        if "obsolete" not in obj:
            fout.write(">{}|{}\n{}\n".format(obj['disprot_id'], obj['acc'], obj['sequence']))

In [14]:
# Convert json to dataframe
entry_columns = ['disprot_id', 'acc', 'ncbi_taxon_id', 'organism', 'sequence']
df = pd.json_normalize(data=dataset, record_path=['regions'], meta=entry_columns, meta_prefix='', record_prefix='')
df = pd.merge(left=df, right=df_challenge, how="inner", on="term_id")
df.to_csv(dataset_raw_file, sep="\t", index=False)
df.columns

Index(['term_namespace', 'ec_ontology', 'end', 'region_id', 'start', 'term_id',
       'unpublished', 'statement', 'curator_id', 'released', 'ec_name',
       'term_ontology', 'curator_name', 'reference_id', 'version',
       'reference_html', 'date', 'reference_source', 'ec_id', 'cross_refs',
       'term_name_x', 'curator_orcid', 'ec_go', 'disprot_namespace',
       'validated.curator_name', 'validated.curator_id', 'validated.timestamp',
       'term_comment', 'term_def', 'term_is_obsolete', 'term_not_annotate',
       'interaction_partner', 'construct_alterations', 'sample',
       'sequence_construct', 'conditions', 'states_connection', 'disprot_id',
       'acc', 'ncbi_taxon_id', 'organism', 'sequence', 'challenge',
       'term_name_y'],
      dtype='object')

In [15]:
region_columns = ["start", "end", "term_id", "ec_id", "challenge"]
df = df.loc[:, entry_columns + region_columns]
df

,disprot_id,acc,ncbi_taxon_id,organism,sequence,start,end,term_id,ec_id,challenge
0,DP02732,Q8IWJ2,9606,Homo sapiens,MEDLVQDGVASPATPGTGKSKLETLPKEDLIKFAKKQMMLIQKAKS...,1547,1569,IDPO:00076,ECO:0006220,disorder
1,DP03745,Q8VHC3,10090,Mus musculus,MSILLSPPSLLLLLAALVAPATSTTNYRPDWNRLRGLARGRVETCG...,25,34,IDPO:00076,ECO:0001238,disorder
2,DP03745,Q8VHC3,10090,Mus musculus,MSILLSPPSLLLLLAALVAPATSTTNYRPDWNRLRGLARGRVETCG...,121,145,IDPO:00076,ECO:0001238,disorder
3,DP03748,P75862,83333,Escherichia coli (strain K12),MRIKPDDNWRWYYDEEHDRMMLDLANGMLFRSRFARKMLTPDAFSP...,169,180,IDPO:00076,ECO:0006220,disorder
4,DP03749,Q92871,9606,Homo sapiens,MAVTAQAARRKERVLCLFDVDGTLTPARQKIDPEVAAFLQKLRSRV...,1,11,IDPO:00076,ECO:0006220,disorder
...,...,...,...,...,...,...,...,...,...,...
717,DP04239,P53355,9606,Homo sapiens,MTVFRQENVDDYYDTGEELGSGQFAVVKKCREKSTGLQYAAKFIKK...,302,320,GO:0005516,ECO:0005647,binding protein
718,DP04241,P15146-3,10116,Rattus norvegicus,MADERKDEGKAPHWTSASLTEAAAHPHSPEMKDQGGSGEGLSRSAN...,1,159,GO:0019901,ECO:0005647,binding
719,DP04241,P15146-3,10116,Rattus norvegicus,MADERKDEGKAPHWTSASLTEAAAHPHSPEMKDQGGSGEGLSRSAN...,1,159,GO:0019901,ECO:0005647,binding protein
720,DP04241,P15146-3,10116,Rattus norvegicus,MADERKDEGKAPHWTSASLTEAAAHPHSPEMKDQGGSGEGLSRSAN...,80,118,GO:0019901,ECO:0006165,binding
721,DP04241,P15146-3,10116,Rattus norvegicus,MADERKDEGKAPHWTSASLTEAAAHPHSPEMKDQGGSGEGLSRSAN...,80,118,GO:0019901,ECO:0006165,binding protein

In [16]:
# Get dataset sequences (1 residue per row)
df_sequence = df.apply(expand_sequence, axis=1).copy(deep=True).drop(columns=["ncbi_taxon_id", "organism", "start", "end", "sequence", "term_id", "ec_id", 'challenge'])
df_sequence = df_sequence.explode("seq_aa")
df_sequence[['pos', 'aa']] = pd.DataFrame(df_sequence['seq_aa'].tolist(), index=df_sequence.index)
df_sequence = df_sequence.drop(columns='seq_aa').drop_duplicates()
df_sequence

    disprot_id     acc  pos aa
0      DP02732  Q8IWJ2    1  M
0      DP02732  Q8IWJ2    2  E
0      DP02732  Q8IWJ2    3  D
0      DP02732  Q8IWJ2    4  L
0      DP02732  Q8IWJ2    5  V
..         ...     ...  ... ..
428    DP04246  Q4KL64  214  R
428    DP04246  Q4KL64  215  R
428    DP04246  Q4KL64  216  D
428    DP04246  Q4KL64  217  T
428    DP04246  Q4KL64  218  S

[117053 rows x 4 columns]

## Map PDB observed positions using SIFTS

In [17]:
df_sifts = pd.read_csv(sifts_file, sep="\t", header=1)
# Filter for dataset entries
df_sifts = df_sifts.loc[df_sifts['SP_PRIMARY'].isin(df_sequence['acc'])]
# Explode observed regions 
df_sifts = df_sifts.apply(expand_region, start_col="SP_BEG", end_col="SP_END", axis=1)
df_sifts = df_sifts.explode("reg_position")
df_sifts = df_sifts.loc[:, ['SP_PRIMARY', 'reg_position']].drop_duplicates().reset_index(drop=True).rename(columns={"SP_PRIMARY": "acc"})
df_sifts

          acc reg_position
0      P0A8P8            3
1      P0A8P8            4
2      P0A8P8            5
3      P0A8P8            6
4      P0A8P8            7
...       ...          ...
50910  P45973          189
50911  P45973          190
50912  P45973          191
50913  Q9Y4B6         1325
50914  Q9Y4B6         1324

[50915 rows x 2 columns]

In [18]:
df_sequence = pd.merge(df_sequence, df_sifts, left_on=["acc", "pos"], right_on=["acc", "reg_position"], how="left")
df_sequence.rename(columns={"reg_position": "pdb"}, inplace=True)
df_sequence.loc[df_sequence['pdb'].notnull(), 'pdb'] = 1.0
df_sequence.loc[df_sequence['pdb'].notnull()]

       disprot_id     acc   pos aa  pdb
1569      DP02732  Q8IWJ2  1570  K  1.0
1570      DP02732  Q8IWJ2  1571  S  1.0
1571      DP02732  Q8IWJ2  1572  A  1.0
1572      DP02732  Q8IWJ2  1573  D  1.0
1573      DP02732  Q8IWJ2  1574  H  1.0
...           ...     ...   ... ..  ...
116980    DP04246  Q4KL64   146  D  1.0
116981    DP04246  Q4KL64   147  I  1.0
116982    DP04246  Q4KL64   148  Q  1.0
116983    DP04246  Q4KL64   149  L  1.0
116984    DP04246  Q4KL64   150  V  1.0

[50915 rows x 5 columns]

## Define regions

Transform the per-protein dataframe into a per-residue dataframe

In [19]:
df_regions = df.apply(expand_region, axis=1).loc[:, ["disprot_id", "reg_position", "ec_id", "challenge"]].copy(deep=True)
# df_regions = pd.merge(left=df_regions, right=df_challenge, how="inner", left_on="term_id", right_on="term_id").drop(columns=["term_id"])
df_regions

,disprot_id,reg_position,ec_id,challenge
0,DP02732,"[1547, 1548, 1549, 1550, 1551, 1552, 1553, 155...",ECO:0006220,disorder
1,DP03745,"[25, 26, 27, 28, 29, 30, 31, 32, 33, 34]",ECO:0001238,disorder
2,DP03745,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...",ECO:0001238,disorder
3,DP03748,"[169, 170, 171, 172, 173, 174, 175, 176, 177, ...",ECO:0006220,disorder
4,DP03749,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]",ECO:0006220,disorder
...,...,...,...,...
717,DP04239,"[302, 303, 304, 305, 306, 307, 308, 309, 310, ...",ECO:0005647,binding protein
718,DP04241,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",ECO:0005647,binding
719,DP04241,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",ECO:0005647,binding protein
720,DP04241,"[80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 9...",ECO:0006165,binding
721,DP04241,"[80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 9...",ECO:0006165,binding protein

In [20]:
# ECO:0006220, X-ray crystallography-based structural model with missing residue coordinates used in manual assertion  
df_ = df_regions.loc[(df_regions['challenge'] == 'disorder') & (df_regions['ec_id'] != 'ECO:0006220')]
df_.loc[:, 'challenge'] = 'disorder_nox'
df_regions = pd.concat([df_regions, df_])
df_regions

,disprot_id,reg_position,ec_id,challenge
0,DP02732,"[1547, 1548, 1549, 1550, 1551, 1552, 1553, 155...",ECO:0006220,disorder
1,DP03745,"[25, 26, 27, 28, 29, 30, 31, 32, 33, 34]",ECO:0001238,disorder
2,DP03745,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...",ECO:0001238,disorder
3,DP03748,"[169, 170, 171, 172, 173, 174, 175, 176, 177, ...",ECO:0006220,disorder
4,DP03749,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]",ECO:0006220,disorder
...,...,...,...,...
674,DP04151,"[162, 163, 164, 165, 166, 167, 168, 169, 170, ...",ECO:0001184,disorder_nox
675,DP04151,"[162, 163, 164, 165, 166, 167, 168, 169, 170, ...",ECO:0006204,disorder_nox
676,DP04152,"[163, 164, 165, 166, 167, 168, 169, 170, 171, ...",ECO:0001184,disorder_nox
677,DP04152,"[163, 164, 165, 166, 167, 168, 169, 170, 171, ...",ECO:0006204,disorder_nox
678,DP04154,"[156, 157, 158, 159, 160, 161, 162, 163, 164, ...",ECO:0007689,disorder_nox

In [21]:
df_regions_all = df_regions.drop(columns=['ec_id']).explode("reg_position").drop_duplicates()
df_regions_all['has_region'] = 1
df_regions_all

    disprot_id reg_position     challenge  has_region
0      DP02732         1547      disorder           1
0      DP02732         1548      disorder           1
0      DP02732         1549      disorder           1
0      DP02732         1550      disorder           1
0      DP02732         1551      disorder           1
..         ...          ...           ...         ...
428    DP04246           69  disorder_nox           1
428    DP04246           70  disorder_nox           1
428    DP04246           71  disorder_nox           1
428    DP04246           72  disorder_nox           1
428    DP04246           73  disorder_nox           1

[49591 rows x 4 columns]

In [22]:
# Create the pivot table. Transpose challenge values into columns 
df_regions_all = pd.pivot_table(
    df_regions_all,
    columns="challenge",
    index=['disprot_id', 'reg_position'],
    values='has_region')
df_regions_all = df_regions_all.reset_index()
df_regions_all

challenge,disprot_id,reg_position,binding,binding nucleic acid,binding protein,disorder,disorder_nox,linker,transition
0,DP02732,1547,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,DP02732,1548,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,DP02732,1549,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,DP02732,1550,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,DP02732,1551,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
20913,DP04246,69,NaN,NaN,NaN,1.0,1.0,NaN,NaN
20914,DP04246,70,NaN,NaN,NaN,1.0,1.0,NaN,NaN
20915,DP04246,71,NaN,NaN,NaN,1.0,1.0,NaN,NaN
20916,DP04246,72,NaN,NaN,NaN,1.0,1.0,NaN,NaN
20917,DP04246,73,NaN,NaN,NaN,1.0,1.0,NaN,NaN

In [23]:
# Add sequence positions not mapping to any DisProt region
df_regions_all = pd.merge(left=df_regions_all, right=df_sequence, how="right", left_on=["disprot_id", "reg_position"], right_on=["disprot_id", "pos"])
df_regions_all.drop(columns="reg_position", inplace=True)
df_regions_all

,disprot_id,binding,binding nucleic acid,binding protein,disorder,disorder_nox,linker,transition,acc,pos,aa,pdb
0,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,1,M,NaN
1,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,2,E,NaN
2,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,3,D,NaN
3,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,4,L,NaN
4,DP02732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q8IWJ2,5,V,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
117048,DP04246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q4KL64,214,R,NaN
117049,DP04246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q4KL64,215,R,NaN
117050,DP04246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q4KL64,216,D,NaN
117051,DP04246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q4KL64,217,T,NaN
117052,DP04246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q4KL64,218,S,NaN

## Write files

Challenge definitions

- The first list are the columns to be considered as positive (any)
- The second list (mask) are the columns to be considered as negative (any)
- If the second list is not provided all non-positives are considered negatives
- In case of conflicts, the positives always overwrite the negatives
- If mask is provided proteins without at least one residue that could be masked (even when overwritten by a positive) are excluded (e.g. only proteins with PDB observed residues are considered)

In [24]:
# Reorder the columns
head_cols = ['disprot_id', 'acc', 'pos', 'aa']
disprot_cols = list(df_challenge['challenge'].unique())
other_cols = sorted(list((set(df_regions_all.columns.tolist()) - set(head_cols)) - set(disprot_cols)))
cols = head_cols + disprot_cols + other_cols
df_regions_all = df_regions_all[cols]
df_regions_all

,disprot_id,acc,pos,aa,disorder,linker,transition,binding nucleic acid,binding,binding protein,disorder_nox,pdb
0,DP02732,Q8IWJ2,1,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DP02732,Q8IWJ2,2,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DP02732,Q8IWJ2,3,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DP02732,Q8IWJ2,4,L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DP02732,Q8IWJ2,5,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
117048,DP04246,Q4KL64,214,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117049,DP04246,Q4KL64,215,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117050,DP04246,Q4KL64,216,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117051,DP04246,Q4KL64,217,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117052,DP04246,Q4KL64,218,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# Write the dataframe
df_regions_all.to_csv(dataset_file, sep="\t", index=False)

### Write references (Fasta format)

* The next element overwrites the previous in the "class" list
* The "fill" field is used to fill unassigned positions
* Only proteins with at least a "1" are written to file

In [26]:
challenges = {'linker': {'class': [('linker', '1')], 'fill': '0'}, 
              'linker_disorder': {'class': [('disorder', '0'), ('linker', '1')], 'fill': '-'},
              'disorder': {'class': [('disorder', '1')], 'fill': '0'}, 
              'disorder_nox': {'class': [('disorder_nox', '1')], 'fill': '0'}, 
              'disorder_pdb': {'class': [('pdb', '0'), ('disorder', '1')], 'fill': '-'},
              'disorder_pdb_fill': {'class': [('pdb', '0'), ('disorder', '1')], 'fill': '1'},
              'binding': {'class': [('binding', '1')], 'fill': '0'},
              'binding_nucleic_acid': {'class': [('binding nucleic acid', '1')], 'fill': '0'},
              'binding_disorder': {'class': [('disorder', '0'), ('binding', '1')], 'fill': '-'},
             }

for file_name, challenge in challenges.items():
    with open("{}/{}.fasta".format(references_dir, file_name), "w") as fout:
        for disprot_id, df_g in df_regions_all.groupby('disprot_id'):
            df_g['output'] = np.nan
            # Assign class
            for column, value in challenge['class']:
                df_g.loc[df_g[column].notnull(), 'output'] = value
            # Fill
            if df_g['output'].notnull().any() and challenge.get('fill'):
                df_g.loc[df_g['output'].isnull(), 'output'] = challenge['fill'] 
            # Write proteins with at least one positive assignment
            if (df_g['output'] == '1').any():
                fout.write(">{}\n{}\n{}\n".format(disprot_id, "".join(df_g['aa']), "".join(df_g['output'])))