In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset_merge_file = "../data/output/dataset_merge.tsv"

# output
figures_dir = "../data/output/references_merge_analysis"
disprot_delta_file = "../data/output/disprot_delta.tsv"

In [3]:
df_dataset = pd.read_csv(dataset_merge_file, sep="\t", header=[0,1], index_col=[0,1,2,3,4])
df_dataset

                               reference                    \
                                disorder linker transition
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M        NaN    NaN        NaN
1     DP02732    Q8IWJ2 2   E        NaN    NaN        NaN
2     DP02732    Q8IWJ2 3   D        NaN    NaN        NaN
3     DP02732    Q8IWJ2 4   L        NaN    NaN        NaN
4     DP02732    Q8IWJ2 5   V        NaN    NaN        NaN
...                                  ...    ...        ...
95449 DP04186    C7G3K3 76  D        NaN    NaN        NaN
95450 DP04186    C7G3K3 77  C        NaN    NaN        NaN
95451 DP04186    C7G3K3 78  V        NaN    NaN        NaN
95452 DP04186    C7G3K3 79  C        NaN    NaN        NaN
95453 DP04186    C7G3K3 80  S        NaN    NaN        NaN

                                                                             \
                               binding nucleic acid binding binding protein
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                   NaN     NaN             NaN
1     DP02732    Q8IWJ2 2   E                   NaN     NaN             NaN
2     DP02732    Q8IWJ2 3   D                   NaN     NaN             NaN
3     DP02732    Q8IWJ2 4   L                   NaN     NaN             NaN
4     DP02732    Q8IWJ2 5   V                   NaN     NaN             NaN
...                                             ...     ...             ...
95449 DP04186    C7G3K3 76  D                   NaN     NaN             NaN
95450 DP04186    C7G3K3 77  C                   NaN     NaN             NaN
95451 DP04186    C7G3K3 78  V                   NaN     NaN             NaN
95452 DP04186    C7G3K3 79  C                   NaN     NaN             NaN
95453 DP04186    C7G3K3 80  S                   NaN     NaN             NaN

                                                 disorder                     \
                               disorder_nox  pdb  AIUPred AIUPred-2-disorder
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M           NaN  NaN      1.0                1.0
1     DP02732    Q8IWJ2 2   E           NaN  NaN      1.0                1.0
2     DP02732    Q8IWJ2 3   D           NaN  NaN      1.0                1.0
3     DP02732    Q8IWJ2 4   L           NaN  NaN      1.0                1.0
4     DP02732    Q8IWJ2 5   V           NaN  NaN      1.0                1.0
...                                     ...  ...      ...                ...
95449 DP04186    C7G3K3 76  D           NaN  1.0      0.0                NaN
95450 DP04186    C7G3K3 77  C           NaN  1.0      0.0                NaN
95451 DP04186    C7G3K3 78  V           NaN  1.0      1.0                NaN
95452 DP04186    C7G3K3 79  C           NaN  1.0      1.0                NaN
95453 DP04186    C7G3K3 80  S           NaN  1.0      1.0                NaN

                                ...         binding                \
                                ... MoRFchibi-light MoRFchibi-web
      disprot_id acc    pos aa  ...
0     DP02732    Q8IWJ2 1   M   ...             1.0           1.0
1     DP02732    Q8IWJ2 2   E   ...             1.0           1.0
2     DP02732    Q8IWJ2 3   D   ...             1.0           1.0
3     DP02732    Q8IWJ2 4   L   ...             1.0           1.0
4     DP02732    Q8IWJ2 5   V   ...             0.0           1.0
...                             ...             ...           ...
95449 DP04186    C7G3K3 76  D   ...             1.0           1.0
95450 DP04186    C7G3K3 77  C   ...             1.0           1.0
95451 DP04186    C7G3K3 78  V   ...             1.0           1.0
95452 DP04186    C7G3K3 79  C   ...             1.0           1.0
95453 DP04186    C7G3K3 80  S   ...             1.0           1.0

                                                                      \
                               NeProc-binding OPAL ProBiPred-nucleic
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M             1.0  1.0               0.0
1     DP02732    Q8IWJ2 2   E             1.0  1.0               0.0
2     DP02732    Q8IWJ2 3   D             1.0  1.0               0.0
3     DP02732    Q8IWJ2 4   L             1.0  1.0               0.0
4     DP02732    Q8IWJ2 5   V             1.0  1.0               0.0
...                                       ...  ...               ...
95449 DP04186    C7G3K3 76  D             0.0  1.0               0.0
95450 DP04186    C7G3K3 77  C             0.0  1.0               0.0
95451 DP04186    C7G3K3 78  V             0.0  1.0               0.0
95452 DP04186    C7G3K3 79  C             0.0  1.0               0.0
95453 DP04186    C7G3K3 80  S             0.0  1.0               0.0

                                                                            \
                               ProBiPred-protein bindEmbed21IDR-idrGeneral
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                1.0                       1.0
1     DP02732    Q8IWJ2 2   E                1.0                       1.0
2     DP02732    Q8IWJ2 3   D                1.0                       1.0
3     DP02732    Q8IWJ2 4   L                1.0                       1.0
4     DP02732    Q8IWJ2 5   V                1.0                       1.0
...                                          ...                       ...
95449 DP04186    C7G3K3 76  D                1.0                       1.0
95450 DP04186    C7G3K3 77  C                1.0                       1.0
95451 DP04186    C7G3K3 78  V                1.0                       1.0
95452 DP04186    C7G3K3 79  C                1.0                       1.0
95453 DP04186    C7G3K3 80  S                1.0                       1.0

                                                      \
                               bindEmbed21IDR-idrNuc
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                    1.0
1     DP02732    Q8IWJ2 2   E                    1.0
2     DP02732    Q8IWJ2 3   D                    1.0
3     DP02732    Q8IWJ2 4   L                    1.0
4     DP02732    Q8IWJ2 5   V                    1.0
...                                              ...
95449 DP04186    C7G3K3 76  D                    1.0
95450 DP04186    C7G3K3 77  C                    1.0
95451 DP04186    C7G3K3 78  V                    1.0
95452 DP04186    C7G3K3 79  C                    1.0
95453 DP04186    C7G3K3 80  S                    1.0


                               bindEmbed21IDR-rawGeneral bindEmbed21IDR-rawNuc
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                        1.0                   1.0
1     DP02732    Q8IWJ2 2   E                        1.0                   1.0
2     DP02732    Q8IWJ2 3   D                        1.0                   1.0
3     DP02732    Q8IWJ2 4   L                        1.0                   1.0
4     DP02732    Q8IWJ2 5   V                        1.0                   1.0
...                                                  ...                   ...
95449 DP04186    C7G3K3 76  D                        1.0                   1.0
95450 DP04186    C7G3K3 77  C                        1.0                   1.0
95451 DP04186    C7G3K3 78  V                        1.0                   1.0
95452 DP04186    C7G3K3 79  C                        1.0                   1.0
95453 DP04186    C7G3K3 80  S                        1.0                   1.0

[95454 rows x 110 columns]

In [4]:
df_dataset['disorder-mean'] = df_dataset.loc[:, ('disorder', )].mean(axis=1)
df_dataset['binding-mean'] = df_dataset.loc[:, ('binding', )].mean(axis=1)
df_dataset

/tmp/ipykernel_709959/446397907.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_dataset['disorder-mean'] = df_dataset.loc[:, ('disorder', )].mean(axis=1)
/tmp/ipykernel_709959/446397907.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_dataset['binding-mean'] = df_dataset.loc[:, ('binding', )].mean(axis=1)

                               reference                    \
                                disorder linker transition
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M        NaN    NaN        NaN
1     DP02732    Q8IWJ2 2   E        NaN    NaN        NaN
2     DP02732    Q8IWJ2 3   D        NaN    NaN        NaN
3     DP02732    Q8IWJ2 4   L        NaN    NaN        NaN
4     DP02732    Q8IWJ2 5   V        NaN    NaN        NaN
...                                  ...    ...        ...
95449 DP04186    C7G3K3 76  D        NaN    NaN        NaN
95450 DP04186    C7G3K3 77  C        NaN    NaN        NaN
95451 DP04186    C7G3K3 78  V        NaN    NaN        NaN
95452 DP04186    C7G3K3 79  C        NaN    NaN        NaN
95453 DP04186    C7G3K3 80  S        NaN    NaN        NaN

                                                                             \
                               binding nucleic acid binding binding protein
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                   NaN     NaN             NaN
1     DP02732    Q8IWJ2 2   E                   NaN     NaN             NaN
2     DP02732    Q8IWJ2 3   D                   NaN     NaN             NaN
3     DP02732    Q8IWJ2 4   L                   NaN     NaN             NaN
4     DP02732    Q8IWJ2 5   V                   NaN     NaN             NaN
...                                             ...     ...             ...
95449 DP04186    C7G3K3 76  D                   NaN     NaN             NaN
95450 DP04186    C7G3K3 77  C                   NaN     NaN             NaN
95451 DP04186    C7G3K3 78  V                   NaN     NaN             NaN
95452 DP04186    C7G3K3 79  C                   NaN     NaN             NaN
95453 DP04186    C7G3K3 80  S                   NaN     NaN             NaN

                                                 disorder                     \
                               disorder_nox  pdb  AIUPred AIUPred-2-disorder
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M           NaN  NaN      1.0                1.0
1     DP02732    Q8IWJ2 2   E           NaN  NaN      1.0                1.0
2     DP02732    Q8IWJ2 3   D           NaN  NaN      1.0                1.0
3     DP02732    Q8IWJ2 4   L           NaN  NaN      1.0                1.0
4     DP02732    Q8IWJ2 5   V           NaN  NaN      1.0                1.0
...                                     ...  ...      ...                ...
95449 DP04186    C7G3K3 76  D           NaN  1.0      0.0                NaN
95450 DP04186    C7G3K3 77  C           NaN  1.0      0.0                NaN
95451 DP04186    C7G3K3 78  V           NaN  1.0      1.0                NaN
95452 DP04186    C7G3K3 79  C           NaN  1.0      1.0                NaN
95453 DP04186    C7G3K3 80  S           NaN  1.0      1.0                NaN

                                ...        binding                         \
                                ... NeProc-binding OPAL ProBiPred-nucleic
      disprot_id acc    pos aa  ...
0     DP02732    Q8IWJ2 1   M   ...            1.0  1.0               0.0
1     DP02732    Q8IWJ2 2   E   ...            1.0  1.0               0.0
2     DP02732    Q8IWJ2 3   D   ...            1.0  1.0               0.0
3     DP02732    Q8IWJ2 4   L   ...            1.0  1.0               0.0
4     DP02732    Q8IWJ2 5   V   ...            1.0  1.0               0.0
...                             ...            ...  ...               ...
95449 DP04186    C7G3K3 76  D   ...            0.0  1.0               0.0
95450 DP04186    C7G3K3 77  C   ...            0.0  1.0               0.0
95451 DP04186    C7G3K3 78  V   ...            0.0  1.0               0.0
95452 DP04186    C7G3K3 79  C   ...            0.0  1.0               0.0
95453 DP04186    C7G3K3 80  S   ...            0.0  1.0               0.0

                                                                            \
                               ProBiPred-protein bindEmbed21IDR-idrGeneral
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                1.0                       1.0
1     DP02732    Q8IWJ2 2   E                1.0                       1.0
2     DP02732    Q8IWJ2 3   D                1.0                       1.0
3     DP02732    Q8IWJ2 4   L                1.0                       1.0
4     DP02732    Q8IWJ2 5   V                1.0                       1.0
...                                          ...                       ...
95449 DP04186    C7G3K3 76  D                1.0                       1.0
95450 DP04186    C7G3K3 77  C                1.0                       1.0
95451 DP04186    C7G3K3 78  V                1.0                       1.0
95452 DP04186    C7G3K3 79  C                1.0                       1.0
95453 DP04186    C7G3K3 80  S                1.0                       1.0

                                                      \
                               bindEmbed21IDR-idrNuc
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                    1.0
1     DP02732    Q8IWJ2 2   E                    1.0
2     DP02732    Q8IWJ2 3   D                    1.0
3     DP02732    Q8IWJ2 4   L                    1.0
4     DP02732    Q8IWJ2 5   V                    1.0
...                                              ...
95449 DP04186    C7G3K3 76  D                    1.0
95450 DP04186    C7G3K3 77  C                    1.0
95451 DP04186    C7G3K3 78  V                    1.0
95452 DP04186    C7G3K3 79  C                    1.0
95453 DP04186    C7G3K3 80  S                    1.0

                                                          \
                               bindEmbed21IDR-rawGeneral
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                        1.0
1     DP02732    Q8IWJ2 2   E                        1.0
2     DP02732    Q8IWJ2 3   D                        1.0
3     DP02732    Q8IWJ2 4   L                        1.0
4     DP02732    Q8IWJ2 5   V                        1.0
...                                                  ...
95449 DP04186    C7G3K3 76  D                        1.0
95450 DP04186    C7G3K3 77  C                        1.0
95451 DP04186    C7G3K3 78  V                        1.0
95452 DP04186    C7G3K3 79  C                        1.0
95453 DP04186    C7G3K3 80  S                        1.0

                                                     disorder-mean  \
                               bindEmbed21IDR-rawNuc
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                    1.0      0.808745
1     DP02732    Q8IWJ2 2   E                    1.0      0.816509
2     DP02732    Q8IWJ2 3   D                    1.0      0.819328
3     DP02732    Q8IWJ2 4   L                    1.0      0.822610
4     DP02732    Q8IWJ2 5   V                    1.0      0.833912
...                                              ...           ...
95449 DP04186    C7G3K3 76  D                    1.0      0.372075
95450 DP04186    C7G3K3 77  C                    1.0      0.401370
95451 DP04186    C7G3K3 78  V                    1.0      0.388887
95452 DP04186    C7G3K3 79  C                    1.0      0.455741
95453 DP04186    C7G3K3 80  S                    1.0      0.548556

                               binding-mean

      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M      0.881667
1     DP02732    Q8IWJ2 2   E      0.853250
2     DP02732    Q8IWJ2 3   D      0.909056
3     DP02732    Q8IWJ2 4   L      0.881139
4     DP02732    Q8IWJ2 5   V      0.906400
...                                     ...
95449 DP04186    C7G3K3 76  D      0.585857
95450 DP04186    C7G3K3 77  C      0.635162
95451 DP04186    C7G3K3 78  V      0.624361
95452 DP04186    C7G3K3 79  C      0.596917
95453 DP04186    C7G3K3 80  S      0.596361

[95454 rows x 112 columns]

In [5]:
# Modify reference values for the figure offset
# df_dataset['af-plddt'] = 1 - df_dataset[('alphafold', 'af-disorder')]
df_dataset.loc[df_dataset[('reference', 'disorder')] == 1, 'disorder-y'] = 1.15
df_dataset.loc[df_dataset[('reference', 'binding')] == 1, 'binding-y'] = 1.1
df_dataset.loc[df_dataset[('reference', 'pdb')] == 1, 'pdb'] = 1.05
df_dataset

                               reference                    \
                                disorder linker transition
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M        NaN    NaN        NaN
1     DP02732    Q8IWJ2 2   E        NaN    NaN        NaN
2     DP02732    Q8IWJ2 3   D        NaN    NaN        NaN
3     DP02732    Q8IWJ2 4   L        NaN    NaN        NaN
4     DP02732    Q8IWJ2 5   V        NaN    NaN        NaN
...                                  ...    ...        ...
95449 DP04186    C7G3K3 76  D        NaN    NaN        NaN
95450 DP04186    C7G3K3 77  C        NaN    NaN        NaN
95451 DP04186    C7G3K3 78  V        NaN    NaN        NaN
95452 DP04186    C7G3K3 79  C        NaN    NaN        NaN
95453 DP04186    C7G3K3 80  S        NaN    NaN        NaN

                                                                             \
                               binding nucleic acid binding binding protein
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                   NaN     NaN             NaN
1     DP02732    Q8IWJ2 2   E                   NaN     NaN             NaN
2     DP02732    Q8IWJ2 3   D                   NaN     NaN             NaN
3     DP02732    Q8IWJ2 4   L                   NaN     NaN             NaN
4     DP02732    Q8IWJ2 5   V                   NaN     NaN             NaN
...                                             ...     ...             ...
95449 DP04186    C7G3K3 76  D                   NaN     NaN             NaN
95450 DP04186    C7G3K3 77  C                   NaN     NaN             NaN
95451 DP04186    C7G3K3 78  V                   NaN     NaN             NaN
95452 DP04186    C7G3K3 79  C                   NaN     NaN             NaN
95453 DP04186    C7G3K3 80  S                   NaN     NaN             NaN

                                                 disorder                     \
                               disorder_nox  pdb  AIUPred AIUPred-2-disorder
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M           NaN  NaN      1.0                1.0
1     DP02732    Q8IWJ2 2   E           NaN  NaN      1.0                1.0
2     DP02732    Q8IWJ2 3   D           NaN  NaN      1.0                1.0
3     DP02732    Q8IWJ2 4   L           NaN  NaN      1.0                1.0
4     DP02732    Q8IWJ2 5   V           NaN  NaN      1.0                1.0
...                                     ...  ...      ...                ...
95449 DP04186    C7G3K3 76  D           NaN  1.0      0.0                NaN
95450 DP04186    C7G3K3 77  C           NaN  1.0      0.0                NaN
95451 DP04186    C7G3K3 78  V           NaN  1.0      1.0                NaN
95452 DP04186    C7G3K3 79  C           NaN  1.0      1.0                NaN
95453 DP04186    C7G3K3 80  S           NaN  1.0      1.0                NaN

                                ...           binding  \
                                ... ProBiPred-protein
      disprot_id acc    pos aa  ...
0     DP02732    Q8IWJ2 1   M   ...               1.0
1     DP02732    Q8IWJ2 2   E   ...               1.0
2     DP02732    Q8IWJ2 3   D   ...               1.0
3     DP02732    Q8IWJ2 4   L   ...               1.0
4     DP02732    Q8IWJ2 5   V   ...               1.0
...                             ...               ...
95449 DP04186    C7G3K3 76  D   ...               1.0
95450 DP04186    C7G3K3 77  C   ...               1.0
95451 DP04186    C7G3K3 78  V   ...               1.0
95452 DP04186    C7G3K3 79  C   ...               1.0
95453 DP04186    C7G3K3 80  S   ...               1.0

                                                          \
                               bindEmbed21IDR-idrGeneral
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                        1.0
1     DP02732    Q8IWJ2 2   E                        1.0
2     DP02732    Q8IWJ2 3   D                        1.0
3     DP02732    Q8IWJ2 4   L                        1.0
4     DP02732    Q8IWJ2 5   V                        1.0
...                                                  ...
95449 DP04186    C7G3K3 76  D                        1.0
95450 DP04186    C7G3K3 77  C                        1.0
95451 DP04186    C7G3K3 78  V                        1.0
95452 DP04186    C7G3K3 79  C                        1.0
95453 DP04186    C7G3K3 80  S                        1.0

                                                      \
                               bindEmbed21IDR-idrNuc
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                    1.0
1     DP02732    Q8IWJ2 2   E                    1.0
2     DP02732    Q8IWJ2 3   D                    1.0
3     DP02732    Q8IWJ2 4   L                    1.0
4     DP02732    Q8IWJ2 5   V                    1.0
...                                              ...
95449 DP04186    C7G3K3 76  D                    1.0
95450 DP04186    C7G3K3 77  C                    1.0
95451 DP04186    C7G3K3 78  V                    1.0
95452 DP04186    C7G3K3 79  C                    1.0
95453 DP04186    C7G3K3 80  S                    1.0

                                                          \
                               bindEmbed21IDR-rawGeneral
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                        1.0
1     DP02732    Q8IWJ2 2   E                        1.0
2     DP02732    Q8IWJ2 3   D                        1.0
3     DP02732    Q8IWJ2 4   L                        1.0
4     DP02732    Q8IWJ2 5   V                        1.0
...                                                  ...
95449 DP04186    C7G3K3 76  D                        1.0
95450 DP04186    C7G3K3 77  C                        1.0
95451 DP04186    C7G3K3 78  V                        1.0
95452 DP04186    C7G3K3 79  C                        1.0
95453 DP04186    C7G3K3 80  S                        1.0

                                                     disorder-mean  \
                               bindEmbed21IDR-rawNuc
      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M                    1.0      0.808745
1     DP02732    Q8IWJ2 2   E                    1.0      0.816509
2     DP02732    Q8IWJ2 3   D                    1.0      0.819328
3     DP02732    Q8IWJ2 4   L                    1.0      0.822610
4     DP02732    Q8IWJ2 5   V                    1.0      0.833912
...                                              ...           ...
95449 DP04186    C7G3K3 76  D                    1.0      0.372075
95450 DP04186    C7G3K3 77  C                    1.0      0.401370
95451 DP04186    C7G3K3 78  V                    1.0      0.388887
95452 DP04186    C7G3K3 79  C                    1.0      0.455741
95453 DP04186    C7G3K3 80  S                    1.0      0.548556

                               binding-mean disorder-y binding-y   pdb

      disprot_id acc    pos aa
0     DP02732    Q8IWJ2 1   M      0.881667        NaN       NaN   NaN
1     DP02732    Q8IWJ2 2   E      0.853250        NaN       NaN   NaN
2     DP02732    Q8IWJ2 3   D      0.909056        NaN       NaN   NaN
3     DP02732    Q8IWJ2 4   L      0.881139        NaN       NaN   NaN
4     DP02732    Q8IWJ2 5   V      0.906400        NaN       NaN   NaN
...                                     ...        ...       ...   ...
95449 DP04186    C7G3K3 76  D      0.585857        NaN       NaN  1.05
95450 DP04186    C7G3K3 77  C      0.635162        NaN       NaN  1.05
95451 DP04186    C7G3K3 78  V      0.624361        NaN       NaN  1.05
95452 DP04186    C7G3K3 79  C      0.596917        NaN       NaN  1.05
95453 DP04186    C7G3K3 80  S      0.596361        NaN       NaN  1.05

[95454 rows x 115 columns]

In [8]:
# Generate all the figures
"""
orange (1.0, 0.4980392156862745, 0.054901960784313725)
red (0.8392156862745098, 0.15294117647058825, 0.1568627450980392)
blue (0.12156862745098039, 0.4666666666666667, 0.7058823529411765)
green (0.17254901960784313, 0.6274509803921569, 0.17254901960784313)
violet (0.5490196078431373, 0.33725490196078434, 0.29411764705882354)
violet2 (0.8901960784313725, 0.4666666666666667, 0.7607843137254902)
gray (0.4980392156862745, 0.4980392156862745, 0.4980392156862745)
yellow (0.7372549019607844, 0.7411764705882353, 0.13333333333333333)
cyan (0.09019607843137255, 0.7450980392156863, 0.8117647058823529)
"""
colors_reference = [(1.0, 0.4980392156862745, 0.054901960784313725),
            (0.8392156862745098, 0.15294117647058825, 0.1568627450980392),
            (0.12156862745098039, 0.4666666666666667, 0.7058823529411765)]

colors_pred = [(1.0, 0.4980392156862745, 0.054901960784313725),
            (0.8392156862745098, 0.15294117647058825, 0.1568627450980392),
            (0.4980392156862745, 0.4980392156862745, 0.4980392156862745)]

for name, df_g in df_dataset.groupby(['disprot_id', 'acc']):
    df_g.reset_index(level='pos', inplace=True)

    fig, axes = plt.subplots(2,1, figsize=(30,10), gridspec_kw={'height_ratios': [2, 6]})
    plt.subplots_adjust(wspace=0, hspace=0)

    # Reference
    df_g.loc[:, [('pos', ''), ('disorder-y', ''), ('binding-y', ''), ('pdb', '')]].plot(
        x='pos', ylim=(0,1.4), grid=True, ax=axes[0], fontsize=18, color=colors_reference, linewidth=6)

    # axes[1].hlines(0.331, xmin=1, xmax=df_g['pos'].max(), lw=1, linestyle='--', color= (0.4980392156862745, 0.4980392156862745, 0.4980392156862745))
    axes[1].hlines(0.5, xmin=1, xmax=df_g['pos'].max(), lw=1, linestyle='-', color='green')

    # Prediction
    df_g.loc[:, [('pos', ''), ('disorder-mean', ''), ('binding-mean', ''), ('disorder', 'AlphaFold-pLDDT')]].plot(
        x='pos', ylim=(0,1.4), grid=True, ax=axes[1], fontsize=18, color=colors_pred, linewidth=3, alpha=0.5)

   

    axes[0].set_title(" - ".join(name), fontdict={'fontsize':18})
    axes[0].set_ylim(1, 1.4)
    axes[0].set_xlim(1, df_g['pos'].max())
    axes[0].axis('off')
    h,_ = axes[0].get_legend_handles_labels()
    axes[0].legend(h, ['Disorder-DisProt', 'Binding-DisProt', 'PDB observed'],
                   prop={'size': 18}, loc='lower left', bbox_to_anchor=(-0.007, 0.5), ncol=3)

    axes[1].set_ylim(0, 1.1)
    axes[1].set_xlim(1, df_g['pos'].max())
    axes[1].xaxis.label.set_visible(False)
    # axes[1].set_yticks(np.arange(0,1.1,0.1))
    axes[1].set_yticks([0, 0.5, 1.0])
    h,_ = axes[1].get_legend_handles_labels()
    axes[1].legend(h, ['Disorder pred. average', 'Binding pred. average', 'AlphaFold-pLDDT'],
                   prop={'size': 18}, loc='lower left', bbox_to_anchor=(0.51, 1.17), ncol=3)

    fig.savefig("{}/{}.png".format(figures_dir, "_".join(name)), bbox_inches='tight', dpi=300)
    plt.close(fig)
    # break

In [10]:
# Find cases where Disprot strongly disagree with AlphaFold
df_ = df_dataset.groupby(['disprot_id', 'acc']).apply(lambda x: ((x['disorder-y'].sum() - x[('disorder', 'AlphaFold-pLDDT')].sum()) * 100 / x.index.get_level_values(3).max(), (x['binding-y'].sum() - x[('binding-mean', '')].sum()) * 100 / x.index.get_level_values(3).max())).reset_index(name='delta')
df_[['delta-disorder', 'delta-binding']] = pd.DataFrame(df_.delta.tolist(), index= df_.index)
df_.drop(columns='delta', inplace=True)
df_.sort_values(['delta-disorder', 'delta-binding'], inplace=True)
df_.to_csv(disprot_delta_file, sep="\t", index=False)
df_

    disprot_id         acc  delta-disorder  delta-binding
159    DP04158      Q9BX66      -51.505495     -68.220125
127    DP04096  A0A0B4JDC9      -48.401085     -57.674117
29     DP03921      A5Y0M2      -46.597407     -42.910812
7      DP03803      Q24459      -43.208629     -59.054358
105    DP04051      Q8IJ45      -35.586745     -60.172809
..         ...         ...             ...            ...
149    DP04147      P97384       91.512724     -44.715419
142    DP04134    O54918-2       92.821429     -44.744493
77     DP04012      Q02973      104.614130     -93.005395
16     DP03819      P56917      115.000000       0.000000
15     DP03818      P57104      115.000000     110.000000

[187 rows x 4 columns]